<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'm_announcement',
'announcement_subject',
'announcement_desc',
'announcement_file',
'announcement_images',
'add_user',
'add_date',
'edit_user',
'edit_date',
'announcement_star_periode',
'announcement_end_periode',
'announcement_active' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'm_announcement' => array( 'import_field' ),
'announcement_subject' => array( 'import_field1' ),
'announcement_desc' => array( 'import_field2' ),
'announcement_file' => array( 'import_field3' ),
'announcement_images' => array( 'import_field4' ),
'add_user' => array( 'import_field5' ),
'add_date' => array( 'import_field6' ),
'edit_user' => array( 'import_field7' ),
'edit_date' => array( 'import_field8' ),
'announcement_star_periode' => array( 'import_field9' ),
'announcement_end_periode' => array( 'import_field10' ),
'announcement_active' => array( 'import_field11' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'm_announcement',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'announcement_subject',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'announcement_desc',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'announcement_file',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'announcement_images',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'add_user',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'add_date',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'edit_user',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'edit_date',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'announcement_star_periode',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'announcement_end_periode',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'announcement_active',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>