<?php
			$optionsArray = array( 'details' => array( 'm_disposition_profile' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'client_type',
'is_active',
'client_name',
'domestic_type_id',
'overseas_type_id',
'client_gender',
'address_domicile_street',
'address_domicile_description',
'address_domicile_postal_code',
'address_domicile_region_id',
'address_domicile_city_id',
'address_domicile_province_id',
'address_domicile_country_id',
'address_correspondence_street',
'address_correspondence_description',
'address_correspondence_postal_code',
'address_correspondence_region_id',
'address_correspondence_city_id',
'address_correspondence_province_id',
'address_correspondence_country_id',
'establishment_place',
'establishment_date',
'tax_number',
'tax_name',
'id_card_number',
'id_card_name',
'id_card_citizen',
'id_card_expired_date',
'contact_pic_name',
'contact_pic_number',
'bank_id',
'bank_swift_code',
'bank_currency',
'bank_account_number',
'dob_place',
'dob_date',
'referral_type',
'referral_partnership',
'referral_marketing',
'referral_employee',
'm_client_profilecol',
'last_user',
'last_date' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'client_type' => array( 'integrated_edit_field' ),
'is_active' => array( 'integrated_edit_field1' ),
'client_name' => array( 'integrated_edit_field8' ),
'domestic_type_id' => array( 'integrated_edit_field9' ),
'overseas_type_id' => array( 'integrated_edit_field10' ),
'client_gender' => array( 'integrated_edit_field11' ),
'address_domicile_street' => array( 'integrated_edit_field12' ),
'address_domicile_description' => array( 'integrated_edit_field13' ),
'address_domicile_postal_code' => array( 'integrated_edit_field14' ),
'address_domicile_region_id' => array( 'integrated_edit_field15' ),
'address_domicile_city_id' => array( 'integrated_edit_field16' ),
'address_domicile_province_id' => array( 'integrated_edit_field17' ),
'address_domicile_country_id' => array( 'integrated_edit_field18' ),
'address_correspondence_street' => array( 'integrated_edit_field19' ),
'address_correspondence_description' => array( 'integrated_edit_field20' ),
'address_correspondence_postal_code' => array( 'integrated_edit_field21' ),
'address_correspondence_region_id' => array( 'integrated_edit_field22' ),
'address_correspondence_city_id' => array( 'integrated_edit_field23' ),
'address_correspondence_province_id' => array( 'integrated_edit_field24' ),
'address_correspondence_country_id' => array( 'integrated_edit_field25' ),
'establishment_place' => array( 'integrated_edit_field26' ),
'establishment_date' => array( 'integrated_edit_field27' ),
'tax_number' => array( 'integrated_edit_field28' ),
'tax_name' => array( 'integrated_edit_field29' ),
'id_card_number' => array( 'integrated_edit_field30' ),
'id_card_name' => array( 'integrated_edit_field31' ),
'id_card_citizen' => array( 'integrated_edit_field32' ),
'id_card_expired_date' => array( 'integrated_edit_field33' ),
'contact_pic_name' => array( 'integrated_edit_field34' ),
'contact_pic_number' => array( 'integrated_edit_field35' ),
'bank_id' => array( 'integrated_edit_field36' ),
'bank_swift_code' => array( 'integrated_edit_field37' ),
'bank_currency' => array( 'integrated_edit_field38' ),
'bank_account_number' => array( 'integrated_edit_field39' ),
'dob_place' => array( 'integrated_edit_field40' ),
'dob_date' => array( 'integrated_edit_field41' ),
'referral_type' => array( 'integrated_edit_field42' ),
'referral_partnership' => array( 'integrated_edit_field43' ),
'referral_marketing' => array( 'integrated_edit_field44' ),
'referral_employee' => array( 'integrated_edit_field45' ),
'm_client_profilecol' => array( 'integrated_edit_field2' ),
'last_user' => array( 'integrated_edit_field3' ),
'last_date' => array( 'integrated_edit_field4' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'add_message' ),
'below-grid' => array( 'add_save',
'add_reset',
'add_back_list',
'add_cancel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'notifications',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array(  ),
'grid' => array( 'section',
'section1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4' ),
'section' => array( 'integrated_edit_field11',
'integrated_edit_field41',
'integrated_edit_field1',
'integrated_edit_field8',
'integrated_edit_field',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field40' ),
'section1' => array( 'integrated_edit_field18',
'integrated_edit_field17',
'integrated_edit_field12',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field13' ),
'section2' => array( 'integrated_edit_field25',
'integrated_edit_field24',
'integrated_edit_field19',
'integrated_edit_field21',
'integrated_edit_field23',
'integrated_edit_field22',
'integrated_edit_field20' ),
'section3' => array( 'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29' ),
'section4' => array( 'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33' ),
'section5' => array( 'integrated_edit_field34',
'integrated_edit_field35' ),
'section6' => array( 'tabs' ),
'section7' => array( 'integrated_edit_field36',
'integrated_edit_field39',
'integrated_edit_field38',
'integrated_edit_field37' ),
'section8' => array( 'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ),
'top' => array(  ) ),
'itemForms' => array( 'add_message' => 'above-grid',
'add_save' => 'below-grid',
'add_reset' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'section' => 'grid',
'section1' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field11' => 'section',
'integrated_edit_field41' => 'section',
'integrated_edit_field1' => 'section',
'integrated_edit_field8' => 'section',
'integrated_edit_field' => 'section',
'integrated_edit_field9' => 'section',
'integrated_edit_field10' => 'section',
'integrated_edit_field40' => 'section',
'integrated_edit_field18' => 'section1',
'integrated_edit_field17' => 'section1',
'integrated_edit_field12' => 'section1',
'integrated_edit_field14' => 'section1',
'integrated_edit_field15' => 'section1',
'integrated_edit_field16' => 'section1',
'integrated_edit_field13' => 'section1',
'integrated_edit_field25' => 'section2',
'integrated_edit_field24' => 'section2',
'integrated_edit_field19' => 'section2',
'integrated_edit_field21' => 'section2',
'integrated_edit_field23' => 'section2',
'integrated_edit_field22' => 'section2',
'integrated_edit_field20' => 'section2',
'integrated_edit_field26' => 'section3',
'integrated_edit_field27' => 'section3',
'integrated_edit_field28' => 'section3',
'integrated_edit_field29' => 'section3',
'integrated_edit_field30' => 'section4',
'integrated_edit_field31' => 'section4',
'integrated_edit_field32' => 'section4',
'integrated_edit_field33' => 'section4',
'integrated_edit_field34' => 'section5',
'integrated_edit_field35' => 'section5',
'tabs' => 'section6',
'integrated_edit_field36' => 'section7',
'integrated_edit_field39' => 'section7',
'integrated_edit_field38' => 'section7',
'integrated_edit_field37' => 'section7',
'integrated_edit_field42' => 'section8',
'integrated_edit_field43' => 'section8',
'integrated_edit_field44' => 'section8',
'integrated_edit_field45' => 'section8' ),
'itemLocations' => array( 'section' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field11' => array( 'location' => 'section',
'cellId' => 'c12' ),
'integrated_edit_field41' => array( 'location' => 'section',
'cellId' => 'c13' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c14' ),
'integrated_edit_field8' => array( 'location' => 'section',
'cellId' => 'c16' ),
'integrated_edit_field' => array( 'location' => 'section',
'cellId' => 'c18' ),
'integrated_edit_field9' => array( 'location' => 'section',
'cellId' => 'c19' ),
'integrated_edit_field10' => array( 'location' => 'section',
'cellId' => 'c20' ),
'integrated_edit_field40' => array( 'location' => 'section',
'cellId' => 'c21' ),
'integrated_edit_field18' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field17' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field12' => array( 'location' => 'section1',
'cellId' => 'c2' ),
'integrated_edit_field14' => array( 'location' => 'section1',
'cellId' => 'c3' ),
'integrated_edit_field15' => array( 'location' => 'section1',
'cellId' => 'c4' ),
'integrated_edit_field16' => array( 'location' => 'section1',
'cellId' => 'c5' ),
'integrated_edit_field13' => array( 'location' => 'section1',
'cellId' => 'c6' ),
'integrated_edit_field25' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field24' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field19' => array( 'location' => 'section2',
'cellId' => 'c2' ),
'integrated_edit_field21' => array( 'location' => 'section2',
'cellId' => 'c3' ),
'integrated_edit_field23' => array( 'location' => 'section2',
'cellId' => 'c4' ),
'integrated_edit_field22' => array( 'location' => 'section2',
'cellId' => 'c5' ),
'integrated_edit_field20' => array( 'location' => 'section2',
'cellId' => 'c6' ),
'integrated_edit_field26' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field27' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field28' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'integrated_edit_field29' => array( 'location' => 'section3',
'cellId' => 'c3' ),
'integrated_edit_field30' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field31' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field32' => array( 'location' => 'section4',
'cellId' => 'c2' ),
'integrated_edit_field33' => array( 'location' => 'section4',
'cellId' => 'c3' ),
'integrated_edit_field34' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field35' => array( 'location' => 'section5',
'cellId' => 'c' ),
'tabs' => array( 'location' => 'section6',
'cellId' => 'c6' ),
'integrated_edit_field36' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field39' => array( 'location' => 'section7',
'cellId' => 'c' ),
'integrated_edit_field38' => array( 'location' => 'section7',
'cellId' => 'c2' ),
'integrated_edit_field37' => array( 'location' => 'section7',
'cellId' => 'c3' ),
'integrated_edit_field42' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field43' => array( 'location' => 'section8',
'cellId' => 'c' ),
'integrated_edit_field44' => array( 'location' => 'section8',
'cellId' => 'c' ),
'integrated_edit_field45' => array( 'location' => 'section8',
'cellId' => 'c' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'add_reset' => array( 'add_reset' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'notifications' => array( 'notifications' ),
'section' => array( 'section',
'section1' ),
'tabs' => array( 'tabs' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section',
'section1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c16' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c20' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c21' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field40' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field41' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field29' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 2 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field30' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field31' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field33' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 2 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field34' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field35' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ),
'section6' => array( 'cells' => array( 'c6' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section7' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field36' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field37' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field38' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field39' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 4 ),
'section8' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field42' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_reset',
'add_back_list',
'add_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'notifications',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'section',
'section1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c16' ),
array( 'cell' => 'c18' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c20' ),
array( 'cell' => 'c19' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ),
array( 'cell' => 'c21' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c13' ),
array( 'cell' => 'c14' ) ) ) ),
'cells' => array( 'c12' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ),
'align' => 'left' ),
'c13' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field41' ) ),
'c14' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ) ),
'c16' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ),
'align' => 'left' ),
'c18' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ) ),
'c19' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c20' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ),
'align' => 'left' ),
'c21' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field40' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field18' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field14' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field16' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13' ) ),
'c7' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field25' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field21' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field23' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field22' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20' ) ),
'c7' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field26' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field27' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field28' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field29' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field30' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field31' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field32' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field33' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field34' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field35' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c6',
'colspan' => 1 ) ) ) ),
'cells' => array( 'c6' => array( 'model' => 'c1',
'items' => array( 'tabs' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section7' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field36' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field39' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field38' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field37' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section8' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field42' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save' ),
'add_reset' => array( 'type' => 'add_reset' ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel' ),
'integrated_edit_field' => array( 'field' => 'client_type',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'is_active',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'client_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'domestic_type_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'overseas_type_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'client_gender',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'address_domicile_street',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'address_domicile_description',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'address_domicile_postal_code',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'address_domicile_region_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'address_domicile_city_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'address_domicile_province_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'address_domicile_country_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'address_correspondence_street',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'address_correspondence_street',
'table' => 'm_client_profile',
'type' => 3 ) ),
'integrated_edit_field20' => array( 'field' => 'address_correspondence_description',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'address_correspondence_description',
'table' => null,
'type' => 3 ) ),
'integrated_edit_field21' => array( 'field' => 'address_correspondence_postal_code',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'address_correspondence_postal_code',
'table' => null,
'type' => 3 ) ),
'integrated_edit_field22' => array( 'field' => 'address_correspondence_region_id',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'address_correspondence_region_id',
'table' => 'm_client_profile',
'type' => 3 ) ),
'integrated_edit_field23' => array( 'field' => 'address_correspondence_city_id',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'address_correspondence_city_id',
'table' => 'm_client_profile',
'type' => 3 ) ),
'integrated_edit_field24' => array( 'field' => 'address_correspondence_province_id',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'address_correspondence_province_id',
'table' => 'm_client_profile',
'type' => 3 ) ),
'integrated_edit_field25' => array( 'field' => 'address_correspondence_country_id',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'address_correspondence_country_id',
'table' => 'm_client_profile',
'type' => 3 ) ),
'integrated_edit_field26' => array( 'field' => 'establishment_place',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'establishment_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'tax_number',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'tax_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'id_card_number',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'id_card_number',
'table' => 'm_client_profile',
'type' => 3 ) ),
'integrated_edit_field31' => array( 'field' => 'id_card_name',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'id_card_name',
'table' => 'm_client_profile',
'type' => 3 ) ),
'integrated_edit_field32' => array( 'field' => 'id_card_citizen',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'id_card_citizen',
'table' => 'm_client_profile',
'type' => 3 ) ),
'integrated_edit_field33' => array( 'field' => 'id_card_expired_date',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'id_card_expired_date',
'table' => 'm_client_profile',
'type' => 3 ) ),
'integrated_edit_field34' => array( 'field' => 'contact_pic_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field35' => array( 'field' => 'contact_pic_number',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field36' => array( 'field' => 'bank_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field37' => array( 'field' => 'bank_swift_code',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field38' => array( 'field' => 'bank_currency',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field39' => array( 'field' => 'bank_account_number',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field40' => array( 'field' => 'dob_place',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field41' => array( 'field' => 'dob_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field42' => array( 'field' => 'referral_type',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field43' => array( 'field' => 'referral_partnership',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'notifications' => array( 'type' => 'notifications' ),
'integrated_edit_field44' => array( 'field' => 'referral_marketing',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field45' => array( 'field' => 'referral_employee',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Client Information, Add New' ),
'location' => 'section',
'bsStyle' => 'default',
'panelType' => 3 ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Domicile',
'type' => 0 ),
array( 'text' => 'Correspondence',
'type' => 0 ),
array( 'text' => 'Establishment',
'type' => 0 ),
array( 'text' => 'ID Card',
'type' => 0 ),
array( 'text' => 'Person in charge',
'type' => 0 ),
array( 'text' => 'Bank Account',
'type' => 0 ),
array( 'text' => 'Business Source',
'type' => 0 ) ),
'locations' => array( 'section1',
'section2',
'section3',
'section4',
'section5',
'section7',
'section8' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'section1' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Client Detail Information' ),
'location' => 'section6',
'bsStyle' => 'default',
'panelType' => 3,
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'panelBorder' => null,
'borderColor' => '',
'initiallyClosed' => true ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'integrated_edit_field2' => array( 'field' => 'm_client_profilecol',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'last_user',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'last_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'pageWidth' => 'full',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>