<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'details' => array( 'm_disposition_profile' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'fields' => array( 'gridFields' => array( 'id',
'client_type',
'is_active',
'is_delete',
'deleted_date',
'client_name',
'domestic_type_id',
'overseas_type_id',
'client_gender',
'address_domicile_street',
'address_domicile_description',
'address_domicile_postal_code',
'address_domicile_region_id',
'address_domicile_city_id',
'address_domicile_province_id',
'address_domicile_country_id',
'address_correspondence_street',
'address_correspondence_description',
'address_correspondence_postal_code',
'address_correspondence_region_id',
'address_correspondence_city_id',
'address_correspondence_province_id',
'address_correspondence_country_id',
'establishment_place',
'establishment_date',
'tax_number',
'tax_name',
'id_card_number',
'id_card_name',
'id_card_citizen',
'id_card_expired_date',
'contact_pic_name',
'contact_pic_number',
'bank_id',
'bank_swift_code',
'bank_currency',
'bank_account_number',
'dob_place',
'dob_date',
'referral_type',
'referral_partnership',
'referral_marketing',
'referral_employee',
'client_no',
'm_client_profilecol',
'last_user',
'last_date' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'integrated_edit_field' ),
'client_type' => array( 'integrated_edit_field1' ),
'is_active' => array( 'integrated_edit_field2' ),
'is_delete' => array( 'integrated_edit_field3' ),
'deleted_date' => array( 'integrated_edit_field4' ),
'client_name' => array( 'integrated_edit_field9' ),
'domestic_type_id' => array( 'integrated_edit_field10' ),
'overseas_type_id' => array( 'integrated_edit_field11' ),
'client_gender' => array( 'integrated_edit_field12' ),
'address_domicile_street' => array( 'integrated_edit_field13' ),
'address_domicile_description' => array( 'integrated_edit_field14' ),
'address_domicile_postal_code' => array( 'integrated_edit_field15' ),
'address_domicile_region_id' => array( 'integrated_edit_field16' ),
'address_domicile_city_id' => array( 'integrated_edit_field17' ),
'address_domicile_province_id' => array( 'integrated_edit_field18' ),
'address_domicile_country_id' => array( 'integrated_edit_field19' ),
'address_correspondence_street' => array( 'integrated_edit_field20' ),
'address_correspondence_description' => array( 'integrated_edit_field21' ),
'address_correspondence_postal_code' => array( 'integrated_edit_field22' ),
'address_correspondence_region_id' => array( 'integrated_edit_field23' ),
'address_correspondence_city_id' => array( 'integrated_edit_field24' ),
'address_correspondence_province_id' => array( 'integrated_edit_field25' ),
'address_correspondence_country_id' => array( 'integrated_edit_field26' ),
'establishment_place' => array( 'integrated_edit_field27' ),
'establishment_date' => array( 'integrated_edit_field28' ),
'tax_number' => array( 'integrated_edit_field29' ),
'tax_name' => array( 'integrated_edit_field30' ),
'id_card_number' => array( 'integrated_edit_field31' ),
'id_card_name' => array( 'integrated_edit_field32' ),
'id_card_citizen' => array( 'integrated_edit_field33' ),
'id_card_expired_date' => array( 'integrated_edit_field34' ),
'contact_pic_name' => array( 'integrated_edit_field35' ),
'contact_pic_number' => array( 'integrated_edit_field36' ),
'bank_id' => array( 'integrated_edit_field37' ),
'bank_swift_code' => array( 'integrated_edit_field38' ),
'bank_currency' => array( 'integrated_edit_field39' ),
'bank_account_number' => array( 'integrated_edit_field40' ),
'dob_place' => array( 'integrated_edit_field41' ),
'dob_date' => array( 'integrated_edit_field42' ),
'referral_type' => array( 'integrated_edit_field43' ),
'referral_partnership' => array( 'integrated_edit_field44' ),
'referral_marketing' => array( 'integrated_edit_field45' ),
'referral_employee' => array( 'integrated_edit_field46' ),
'client_no' => array( 'integrated_edit_field47' ),
'm_client_profilecol' => array( 'integrated_edit_field5' ),
'last_user' => array( 'integrated_edit_field6' ),
'last_date' => array( 'integrated_edit_field7' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'hamburger' ),
'top' => array( 'view_header' ),
'grid' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'view_header' => 'top',
'integrated_edit_field' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field13' => 'grid',
'integrated_edit_field14' => 'grid',
'integrated_edit_field15' => 'grid',
'integrated_edit_field16' => 'grid',
'integrated_edit_field17' => 'grid',
'integrated_edit_field18' => 'grid',
'integrated_edit_field19' => 'grid',
'integrated_edit_field20' => 'grid',
'integrated_edit_field21' => 'grid',
'integrated_edit_field22' => 'grid',
'integrated_edit_field23' => 'grid',
'integrated_edit_field24' => 'grid',
'integrated_edit_field25' => 'grid',
'integrated_edit_field26' => 'grid',
'integrated_edit_field27' => 'grid',
'integrated_edit_field28' => 'grid',
'integrated_edit_field29' => 'grid',
'integrated_edit_field30' => 'grid',
'integrated_edit_field31' => 'grid',
'integrated_edit_field32' => 'grid',
'integrated_edit_field33' => 'grid',
'integrated_edit_field34' => 'grid',
'integrated_edit_field35' => 'grid',
'integrated_edit_field36' => 'grid',
'integrated_edit_field37' => 'grid',
'integrated_edit_field38' => 'grid',
'integrated_edit_field39' => 'grid',
'integrated_edit_field40' => 'grid',
'integrated_edit_field41' => 'grid',
'integrated_edit_field42' => 'grid',
'integrated_edit_field43' => 'grid',
'integrated_edit_field44' => 'grid',
'integrated_edit_field45' => 'grid',
'integrated_edit_field46' => 'grid',
'integrated_edit_field47' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field7' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field21' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field22' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field23' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field24' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field25' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field26' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field27' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field28' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field29' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field30' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field31' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field32' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field33' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field34' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field35' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field36' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field37' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field38' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field39' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field40' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field41' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field42' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field43' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field44' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field45' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field46' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field47' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'view_edit' => array( 'view_edit' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header' ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit' ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'integrated_edit_field' => array( 'field' => 'id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'client_type',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'is_active',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'is_delete',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'deleted_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'client_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'domestic_type_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'overseas_type_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'client_gender',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'address_domicile_street',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'address_domicile_description',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'address_domicile_postal_code',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'address_domicile_region_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'address_domicile_city_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'address_domicile_province_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'address_domicile_country_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'address_correspondence_street',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'address_correspondence_description',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field22' => array( 'field' => 'address_correspondence_postal_code',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field23' => array( 'field' => 'address_correspondence_region_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'address_correspondence_city_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'address_correspondence_province_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'address_correspondence_country_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'establishment_place',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'establishment_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'tax_number',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'tax_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field31' => array( 'field' => 'id_card_number',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field32' => array( 'field' => 'id_card_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field33' => array( 'field' => 'id_card_citizen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field34' => array( 'field' => 'id_card_expired_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field35' => array( 'field' => 'contact_pic_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field36' => array( 'field' => 'contact_pic_number',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field37' => array( 'field' => 'bank_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field38' => array( 'field' => 'bank_swift_code',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field39' => array( 'field' => 'bank_currency',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field40' => array( 'field' => 'bank_account_number',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field41' => array( 'field' => 'dob_place',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field42' => array( 'field' => 'dob_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field43' => array( 'field' => 'referral_type',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field44' => array( 'field' => 'referral_partnership',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field45' => array( 'field' => 'referral_marketing',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field46' => array( 'field' => 'referral_employee',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field47' => array( 'field' => 'client_no',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'm_client_profilecol',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'last_user',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'last_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>