<?php
			$optionsArray = array( 'totals' => array( 'id' => array( 'totalsType' => '' ),
'client_name' => array( 'totalsType' => '' ),
'client_type' => array( 'totalsType' => '' ),
'domestic_type_id' => array( 'totalsType' => '' ),
'overseas_type_id' => array( 'totalsType' => '' ),
'client_gender' => array( 'totalsType' => '' ),
'dob_place' => array( 'totalsType' => '' ),
'dob_date' => array( 'totalsType' => '' ),
'address_domicile_street' => array( 'totalsType' => '' ),
'address_domicile_description' => array( 'totalsType' => '' ),
'address_domicile_postal_code' => array( 'totalsType' => '' ),
'address_domicile_region_id' => array( 'totalsType' => '' ),
'address_domicile_city_id' => array( 'totalsType' => '' ),
'address_domicile_province_id' => array( 'totalsType' => '' ),
'address_domicile_country_id' => array( 'totalsType' => '' ),
'address_correspondence_street' => array( 'totalsType' => '' ),
'address_correspondence_description' => array( 'totalsType' => '' ),
'address_correspondence_postal_code' => array( 'totalsType' => '' ),
'address_correspondence_region_id' => array( 'totalsType' => '' ),
'address_correspondence_city_id' => array( 'totalsType' => '' ),
'address_correspondence_province_id' => array( 'totalsType' => '' ),
'address_correspondence_country_id' => array( 'totalsType' => '' ),
'establishment_place' => array( 'totalsType' => '' ),
'establishment_date' => array( 'totalsType' => '' ),
'tax_number' => array( 'totalsType' => '' ),
'tax_name' => array( 'totalsType' => '' ),
'id_card_number' => array( 'totalsType' => '' ),
'id_card_name' => array( 'totalsType' => '' ),
'id_card_citizen' => array( 'totalsType' => '' ),
'id_card_expired_date' => array( 'totalsType' => '' ),
'contact_pic_name' => array( 'totalsType' => '' ),
'contact_pic_number' => array( 'totalsType' => '' ),
'bank_id' => array( 'totalsType' => '' ),
'bank_swift_code' => array( 'totalsType' => '' ),
'bank_currency' => array( 'totalsType' => '' ),
'bank_account_number' => array( 'totalsType' => '' ),
'referral_type' => array( 'totalsType' => '' ),
'referral_partnership' => array( 'totalsType' => '' ),
'referral_marketing' => array( 'totalsType' => '' ),
'referral_employee' => array( 'totalsType' => '' ),
'is_active' => array( 'totalsType' => '' ),
'is_delete' => array( 'totalsType' => '' ),
'deleted_date' => array( 'totalsType' => '' ),
'add_user' => array( 'totalsType' => '' ),
'add_date' => array( 'totalsType' => '' ),
'edit_user' => array( 'totalsType' => '' ),
'edit_date' => array( 'totalsType' => '' ),
'client_no' => array( 'totalsType' => '' ),
'm_client_profilecol' => array( 'totalsType' => '' ),
'last_user' => array( 'totalsType' => '' ),
'last_date' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id',
'client_type',
'is_active',
'is_delete',
'deleted_date',
'client_name',
'domestic_type_id',
'overseas_type_id',
'client_gender',
'address_domicile_street',
'address_domicile_description',
'address_domicile_postal_code',
'address_domicile_region_id',
'address_domicile_city_id',
'address_domicile_province_id',
'address_domicile_country_id',
'address_correspondence_street',
'address_correspondence_description',
'address_correspondence_postal_code',
'address_correspondence_region_id',
'address_correspondence_city_id',
'address_correspondence_province_id',
'address_correspondence_country_id',
'establishment_place',
'establishment_date',
'tax_number',
'tax_name',
'id_card_number',
'id_card_name',
'id_card_citizen',
'id_card_expired_date',
'contact_pic_name',
'contact_pic_number',
'bank_id',
'bank_swift_code',
'bank_currency',
'bank_account_number',
'dob_place',
'dob_date',
'referral_type',
'referral_partnership',
'referral_marketing',
'referral_employee',
'client_no',
'm_client_profilecol',
'last_user',
'last_date' ),
'exportFields' => array( 'id',
'client_type',
'is_active',
'is_delete',
'deleted_date',
'client_name',
'domestic_type_id',
'overseas_type_id',
'client_gender',
'address_domicile_street',
'address_domicile_description',
'address_domicile_postal_code',
'address_domicile_region_id',
'address_domicile_city_id',
'address_domicile_province_id',
'address_domicile_country_id',
'address_correspondence_street',
'address_correspondence_description',
'address_correspondence_postal_code',
'address_correspondence_region_id',
'address_correspondence_city_id',
'address_correspondence_province_id',
'address_correspondence_country_id',
'establishment_place',
'establishment_date',
'tax_number',
'tax_name',
'id_card_number',
'id_card_name',
'id_card_citizen',
'id_card_expired_date',
'contact_pic_name',
'contact_pic_number',
'bank_id',
'bank_swift_code',
'bank_currency',
'bank_account_number',
'dob_place',
'dob_date',
'referral_type',
'referral_partnership',
'referral_marketing',
'referral_employee',
'client_no',
'm_client_profilecol',
'last_user',
'last_date' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'export_field' ),
'client_type' => array( 'export_field1' ),
'is_active' => array( 'export_field2' ),
'is_delete' => array( 'export_field3' ),
'deleted_date' => array( 'export_field4' ),
'client_name' => array( 'export_field9' ),
'domestic_type_id' => array( 'export_field10' ),
'overseas_type_id' => array( 'export_field11' ),
'client_gender' => array( 'export_field12' ),
'address_domicile_street' => array( 'export_field13' ),
'address_domicile_description' => array( 'export_field14' ),
'address_domicile_postal_code' => array( 'export_field15' ),
'address_domicile_region_id' => array( 'export_field16' ),
'address_domicile_city_id' => array( 'export_field17' ),
'address_domicile_province_id' => array( 'export_field18' ),
'address_domicile_country_id' => array( 'export_field19' ),
'address_correspondence_street' => array( 'export_field20' ),
'address_correspondence_description' => array( 'export_field21' ),
'address_correspondence_postal_code' => array( 'export_field22' ),
'address_correspondence_region_id' => array( 'export_field23' ),
'address_correspondence_city_id' => array( 'export_field24' ),
'address_correspondence_province_id' => array( 'export_field25' ),
'address_correspondence_country_id' => array( 'export_field26' ),
'establishment_place' => array( 'export_field27' ),
'establishment_date' => array( 'export_field28' ),
'tax_number' => array( 'export_field29' ),
'tax_name' => array( 'export_field30' ),
'id_card_number' => array( 'export_field31' ),
'id_card_name' => array( 'export_field32' ),
'id_card_citizen' => array( 'export_field33' ),
'id_card_expired_date' => array( 'export_field34' ),
'contact_pic_name' => array( 'export_field35' ),
'contact_pic_number' => array( 'export_field36' ),
'bank_id' => array( 'export_field37' ),
'bank_swift_code' => array( 'export_field38' ),
'bank_currency' => array( 'export_field39' ),
'bank_account_number' => array( 'export_field40' ),
'dob_place' => array( 'export_field41' ),
'dob_date' => array( 'export_field42' ),
'referral_type' => array( 'export_field43' ),
'referral_partnership' => array( 'export_field44' ),
'referral_marketing' => array( 'export_field45' ),
'referral_employee' => array( 'export_field46' ),
'client_no' => array( 'export_field47' ),
'm_client_profilecol' => array( 'export_field5' ),
'last_user' => array( 'export_field6' ),
'last_date' => array( 'export_field7' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field5',
'export_field6',
'export_field7' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_field36' => 'grid',
'export_field37' => 'grid',
'export_field38' => 'grid',
'export_field39' => 'grid',
'export_field40' => 'grid',
'export_field41' => 'grid',
'export_field42' => 'grid',
'export_field43' => 'grid',
'export_field44' => 'grid',
'export_field45' => 'grid',
'export_field46' => 'grid',
'export_field47' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field5',
'export_field6',
'export_field7' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field5',
'export_field6',
'export_field7' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'client_type',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'is_active',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'is_delete',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'deleted_date',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'client_name',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'domestic_type_id',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'overseas_type_id',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'client_gender',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'address_domicile_street',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'address_domicile_description',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'address_domicile_postal_code',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'address_domicile_region_id',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'address_domicile_city_id',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'address_domicile_province_id',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'address_domicile_country_id',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'address_correspondence_street',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'address_correspondence_description',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'address_correspondence_postal_code',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'address_correspondence_region_id',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'address_correspondence_city_id',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'address_correspondence_province_id',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'address_correspondence_country_id',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'establishment_place',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'establishment_date',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'tax_number',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'tax_name',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'id_card_number',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'id_card_name',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'id_card_citizen',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'id_card_expired_date',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'contact_pic_name',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'contact_pic_number',
'type' => 'export_field' ),
'export_field37' => array( 'field' => 'bank_id',
'type' => 'export_field' ),
'export_field38' => array( 'field' => 'bank_swift_code',
'type' => 'export_field' ),
'export_field39' => array( 'field' => 'bank_currency',
'type' => 'export_field' ),
'export_field40' => array( 'field' => 'bank_account_number',
'type' => 'export_field' ),
'export_field41' => array( 'field' => 'dob_place',
'type' => 'export_field' ),
'export_field42' => array( 'field' => 'dob_date',
'type' => 'export_field' ),
'export_field43' => array( 'field' => 'referral_type',
'type' => 'export_field' ),
'export_field44' => array( 'field' => 'referral_partnership',
'type' => 'export_field' ),
'export_field45' => array( 'field' => 'referral_marketing',
'type' => 'export_field' ),
'export_field46' => array( 'field' => 'referral_employee',
'type' => 'export_field' ),
'export_field47' => array( 'field' => 'client_no',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'm_client_profilecol',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'last_user',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'last_date',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>