<?php
			$optionsArray = array( 'totals' => array( 'm_customer_id' => array( 'totalsType' => '' ),
'm_customer_name' => array( 'totalsType' => '' ),
'm_customer_business_phone' => array( 'totalsType' => '' ),
'm_customer_mobile_phone' => array( 'totalsType' => '' ),
'm_customer_whatsApp' => array( 'totalsType' => '' ),
'm_customer_email' => array( 'totalsType' => '' ),
'm_customer_website' => array( 'totalsType' => '' ),
'm_customer_billing_address' => array( 'totalsType' => '' ),
'm_customer_billing_city' => array( 'totalsType' => '' ),
'm_customer_billing_zipcode' => array( 'totalsType' => '' ),
'm_customer_billing_province' => array( 'totalsType' => '' ),
'm_customer_billing_country' => array( 'totalsType' => '' ),
'm_customer_currency' => array( 'totalsType' => '' ),
'm_customer_contact_fullname' => array( 'totalsType' => '' ),
'm_customer_contact_position' => array( 'totalsType' => '' ),
'm_customer_contact_email' => array( 'totalsType' => '' ),
'm_customer_contact_mobile_phone' => array( 'totalsType' => '' ),
'add_user' => array( 'totalsType' => '' ),
'add_date' => array( 'totalsType' => '' ),
'edit_user' => array( 'totalsType' => '' ),
'edit_date' => array( 'totalsType' => '' ),
'm_customer_status' => array( 'totalsType' => '' ),
'm_customer_no' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'm_customer_id',
'm_customer_name',
'm_customer_business_phone',
'm_customer_mobile_phone',
'm_customer_whatsApp',
'm_customer_email',
'm_customer_website',
'm_customer_billing_address',
'm_customer_billing_city',
'm_customer_billing_zipcode',
'm_customer_billing_province',
'm_customer_billing_country',
'm_customer_currency',
'm_customer_contact_fullname',
'm_customer_contact_position',
'm_customer_contact_email',
'm_customer_contact_mobile_phone',
'add_user',
'add_date',
'edit_user',
'edit_date',
'm_customer_status',
'm_customer_no' ),
'exportFields' => array( 'm_customer_id',
'm_customer_name',
'm_customer_business_phone',
'm_customer_mobile_phone',
'm_customer_whatsApp',
'm_customer_email',
'm_customer_website',
'm_customer_billing_address',
'm_customer_billing_city',
'm_customer_billing_zipcode',
'm_customer_billing_province',
'm_customer_billing_country',
'm_customer_currency',
'm_customer_contact_fullname',
'm_customer_contact_position',
'm_customer_contact_email',
'm_customer_contact_mobile_phone',
'add_user',
'add_date',
'edit_user',
'edit_date',
'm_customer_status',
'm_customer_no' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'm_customer_id' => array( 'export_field' ),
'm_customer_name' => array( 'export_field1' ),
'm_customer_business_phone' => array( 'export_field2' ),
'm_customer_mobile_phone' => array( 'export_field3' ),
'm_customer_whatsApp' => array( 'export_field4' ),
'm_customer_email' => array( 'export_field5' ),
'm_customer_website' => array( 'export_field6' ),
'm_customer_billing_address' => array( 'export_field7' ),
'm_customer_billing_city' => array( 'export_field8' ),
'm_customer_billing_zipcode' => array( 'export_field9' ),
'm_customer_billing_province' => array( 'export_field10' ),
'm_customer_billing_country' => array( 'export_field11' ),
'm_customer_currency' => array( 'export_field12' ),
'm_customer_contact_fullname' => array( 'export_field13' ),
'm_customer_contact_position' => array( 'export_field14' ),
'm_customer_contact_email' => array( 'export_field15' ),
'm_customer_contact_mobile_phone' => array( 'export_field16' ),
'add_user' => array( 'export_field17' ),
'add_date' => array( 'export_field18' ),
'edit_user' => array( 'export_field19' ),
'edit_date' => array( 'export_field20' ),
'm_customer_status' => array( 'export_field21' ),
'm_customer_no' => array( 'export_field22' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'm_customer_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'm_customer_name',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'm_customer_business_phone',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'm_customer_mobile_phone',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'm_customer_whatsApp',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'm_customer_email',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'm_customer_website',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'm_customer_billing_address',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'm_customer_billing_city',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'm_customer_billing_zipcode',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'm_customer_billing_province',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'm_customer_billing_country',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'm_customer_currency',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'm_customer_contact_fullname',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'm_customer_contact_position',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'm_customer_contact_email',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'm_customer_contact_mobile_phone',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'add_user',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'add_date',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'edit_user',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'edit_date',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'm_customer_status',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'm_customer_no',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>