<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'm_mapping_disposition_id',
'm_division_id',
'm_work_unit_id',
'pic_employee_username',
'pic_employee_id',
'pic_employee_fullname',
'pic_employee_email',
'by_employee_username',
'by_employee_id',
'by_employee_fullname',
'by_employee_email',
'm_mapping_disposition_fl',
'pic_employee_level',
'by_employee_level' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'm_mapping_disposition_id' => array( 'import_field' ),
'm_division_id' => array( 'import_field1' ),
'm_work_unit_id' => array( 'import_field2' ),
'pic_employee_username' => array( 'import_field3' ),
'pic_employee_id' => array( 'import_field4' ),
'pic_employee_fullname' => array( 'import_field5' ),
'pic_employee_email' => array( 'import_field6' ),
'by_employee_username' => array( 'import_field7' ),
'by_employee_id' => array( 'import_field8' ),
'by_employee_fullname' => array( 'import_field9' ),
'by_employee_email' => array( 'import_field10' ),
'm_mapping_disposition_fl' => array( 'import_field11' ),
'pic_employee_level' => array( 'import_field12' ),
'by_employee_level' => array( 'import_field13' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'm_mapping_disposition_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'm_division_id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'm_work_unit_id',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'pic_employee_username',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'pic_employee_id',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'pic_employee_fullname',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'pic_employee_email',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'by_employee_username',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'by_employee_id',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'by_employee_fullname',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'by_employee_email',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'm_mapping_disposition_fl',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'pic_employee_level',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'by_employee_level',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>