<?php
			$optionsArray = array( 'totals' => array( 'id' => array( 'totalsType' => '' ),
'user_id_tsun' => array( 'totalsType' => '' ),
'producer_name' => array( 'totalsType' => '' ),
'producer_category_id' => array( 'totalsType' => '' ),
'producer_type_id' => array( 'totalsType' => '' ),
'producer_domestic_type_id' => array( 'totalsType' => '' ),
'producer_overseas_type_id' => array( 'totalsType' => '' ),
'producer_network_association' => array( 'totalsType' => '' ),
'producer_network_company_name' => array( 'totalsType' => '' ),
'producer_gender' => array( 'totalsType' => '' ),
'dob_place' => array( 'totalsType' => '' ),
'dob_date' => array( 'totalsType' => '' ),
'address_street' => array( 'totalsType' => '' ),
'address_description' => array( 'totalsType' => '' ),
'address_postal_code' => array( 'totalsType' => '' ),
'address_region_id' => array( 'totalsType' => '' ),
'address_city_id' => array( 'totalsType' => '' ),
'address_province_id' => array( 'totalsType' => '' ),
'address_country_id' => array( 'totalsType' => '' ),
'establishment_country_id' => array( 'totalsType' => '' ),
'establishment_date' => array( 'totalsType' => '' ),
'licence_nib' => array( 'totalsType' => '' ),
'tax_number' => array( 'totalsType' => '' ),
'tax_name' => array( 'totalsType' => '' ),
'pic_name' => array( 'totalsType' => '' ),
'pic_phone_number' => array( 'totalsType' => '' ),
'agreement_number' => array( 'totalsType' => '' ),
'agreement_period_start' => array( 'totalsType' => '' ),
'agreement_period_end' => array( 'totalsType' => '' ),
'bank_id' => array( 'totalsType' => '' ),
'bank_swift_code' => array( 'totalsType' => '' ),
'bank_account_number' => array( 'totalsType' => '' ),
'is_active' => array( 'totalsType' => '' ),
'is_delete' => array( 'totalsType' => '' ),
'deleted_date' => array( 'totalsType' => '' ),
'created_by' => array( 'totalsType' => '' ),
'created_date' => array( 'totalsType' => '' ),
'last_update_by' => array( 'totalsType' => '' ),
'last_update_date' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id',
'producer_name',
'producer_category_id',
'producer_type_id',
'producer_domestic_type_id',
'producer_overseas_type_id',
'producer_network_association',
'producer_network_company_name',
'producer_gender',
'dob_place',
'dob_date',
'address_street',
'address_description',
'address_postal_code',
'address_region_id',
'address_city_id',
'address_province_id',
'address_country_id',
'establishment_country_id',
'establishment_date',
'licence_nib',
'tax_number',
'tax_name',
'pic_name',
'pic_phone_number',
'agreement_number',
'agreement_period_start',
'agreement_period_end',
'bank_id',
'bank_swift_code',
'bank_account_number',
'is_active',
'is_delete',
'deleted_date',
'created_by',
'created_date',
'last_update_by',
'last_update_date',
'user_id_tsun' ),
'exportFields' => array( 'id',
'producer_name',
'producer_category_id',
'producer_type_id',
'producer_domestic_type_id',
'producer_overseas_type_id',
'producer_network_association',
'producer_network_company_name',
'producer_gender',
'dob_place',
'dob_date',
'address_street',
'address_description',
'address_postal_code',
'address_region_id',
'address_city_id',
'address_province_id',
'address_country_id',
'establishment_country_id',
'establishment_date',
'licence_nib',
'tax_number',
'tax_name',
'pic_name',
'pic_phone_number',
'agreement_number',
'agreement_period_start',
'agreement_period_end',
'bank_id',
'bank_swift_code',
'bank_account_number',
'is_active',
'is_delete',
'deleted_date',
'created_by',
'created_date',
'last_update_by',
'last_update_date',
'user_id_tsun' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'export_field' ),
'producer_name' => array( 'export_field1' ),
'producer_category_id' => array( 'export_field2' ),
'producer_type_id' => array( 'export_field3' ),
'producer_domestic_type_id' => array( 'export_field4' ),
'producer_overseas_type_id' => array( 'export_field5' ),
'producer_network_association' => array( 'export_field6' ),
'producer_network_company_name' => array( 'export_field7' ),
'producer_gender' => array( 'export_field8' ),
'dob_place' => array( 'export_field9' ),
'dob_date' => array( 'export_field10' ),
'address_street' => array( 'export_field11' ),
'address_description' => array( 'export_field12' ),
'address_postal_code' => array( 'export_field13' ),
'address_region_id' => array( 'export_field14' ),
'address_city_id' => array( 'export_field15' ),
'address_province_id' => array( 'export_field16' ),
'address_country_id' => array( 'export_field17' ),
'establishment_country_id' => array( 'export_field18' ),
'establishment_date' => array( 'export_field19' ),
'licence_nib' => array( 'export_field20' ),
'tax_number' => array( 'export_field21' ),
'tax_name' => array( 'export_field22' ),
'pic_name' => array( 'export_field23' ),
'pic_phone_number' => array( 'export_field24' ),
'agreement_number' => array( 'export_field25' ),
'agreement_period_start' => array( 'export_field26' ),
'agreement_period_end' => array( 'export_field27' ),
'bank_id' => array( 'export_field28' ),
'bank_swift_code' => array( 'export_field29' ),
'bank_account_number' => array( 'export_field30' ),
'is_active' => array( 'export_field31' ),
'is_delete' => array( 'export_field32' ),
'deleted_date' => array( 'export_field33' ),
'created_by' => array( 'export_field34' ),
'created_date' => array( 'export_field35' ),
'last_update_by' => array( 'export_field36' ),
'last_update_date' => array( 'export_field37' ),
'user_id_tsun' => array( 'export_field38' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_field36' => 'grid',
'export_field37' => 'grid',
'export_field38' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'producer_name',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'producer_category_id',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'producer_type_id',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'producer_domestic_type_id',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'producer_overseas_type_id',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'producer_network_association',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'producer_network_company_name',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'producer_gender',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'dob_place',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'dob_date',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'address_street',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'address_description',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'address_postal_code',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'address_region_id',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'address_city_id',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'address_province_id',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'address_country_id',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'establishment_country_id',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'establishment_date',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'licence_nib',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'tax_number',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'tax_name',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'pic_name',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'pic_phone_number',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'agreement_number',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'agreement_period_start',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'agreement_period_end',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'bank_id',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'bank_swift_code',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'bank_account_number',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'is_active',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'is_delete',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'deleted_date',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'created_by',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'created_date',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'last_update_by',
'type' => 'export_field' ),
'export_field37' => array( 'field' => 'last_update_date',
'type' => 'export_field' ),
'export_field38' => array( 'field' => 'user_id_tsun',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>