<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'grid' => array( 'dashboard-item',
'dashboard-item9',
'dashboard-item1',
'dashboard-item8',
'dashboard-item2',
'dashboard-item6',
'dashboard-item5',
'dashboard-item7',
'dashboard-item3',
'dashboard-item4' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'notifications',
'username_button' ),
'top' => array(  ) ),
'formXtTags' => array( 'top' => array(  ) ),
'itemForms' => array( 'dashboard-item' => 'grid',
'dashboard-item9' => 'grid',
'dashboard-item1' => 'grid',
'dashboard-item8' => 'grid',
'dashboard-item2' => 'grid',
'dashboard-item6' => 'grid',
'dashboard-item5' => 'grid',
'dashboard-item7' => 'grid',
'dashboard-item3' => 'grid',
'dashboard-item4' => 'grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'notifications' => 'supertop',
'username_button' => 'supertop' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'username_button' => array( 'username_button' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'notifications' => array( 'notifications' ),
'dashboard-item' => array( 'dashboard-item',
'dashboard-item1',
'dashboard-item2',
'dashboard-item3',
'dashboard-item6',
'dashboard-item7',
'dashboard-item4',
'dashboard-item5',
'dashboard-item8',
'dashboard-item9' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'dashboard',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dashboard' => array( 'elements' => array( array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'v1',
'dashType' => 7,
'dashName' => 'v1_snippet',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'file' => 'Out Mail.png' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'mp_tmail_snippet3',
'snippetStyle' => 'right',
'headerColor' => '#a3a3a3',
'bodyBg' => '#fbfbfb',
'bodyColor' => null,
'iconColor' => '#E1A730',
'panelBorder' => '3px',
'borderColor' => '#fbfbfb',
'tabLeaveSpace' => true ),
'elementName' => 'v1_snippet',
'table' => 'v1',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'mp_tmail_snippet3',
'masterTable' => '',
'tabLocation' => 'above',
'tabLeaveSpace' => true,
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'v1',
'dashType' => 7,
'dashName' => 'v1_snippet1',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'file' => 'In Mail.png' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'mp_tmail_snippet4',
'snippetStyle' => 'right',
'headerColor' => '#a3a3a3',
'bodyBg' => '#fbfbfb',
'bodyColor' => null,
'iconColor' => '#E1A730',
'panelBorder' => '3px',
'borderColor' => '#fbfbfb',
'tabLeaveSpace' => true ),
'elementName' => 'v1_snippet1',
'table' => 'v1',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'mp_tmail_snippet4',
'masterTable' => '',
'tabLocation' => 'above',
'tabLeaveSpace' => true,
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'v1',
'dashType' => 7,
'dashName' => 'v1_snippet2',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'file' => 'Processed.png' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'mp_tmail_snippet5',
'headerBg' => '',
'headerColor' => '#a3a3a3',
'bodyBg' => '#fbfbfb',
'bodyColor' => null,
'panelBorder' => '3px',
'borderColor' => '#fbfbfb',
'snippetStyle' => 'left',
'iconColor' => '#E1A730',
'tabLeaveSpace' => true ),
'elementName' => 'v1_snippet2',
'table' => 'v1',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'mp_tmail_snippet5',
'masterTable' => '',
'tabLocation' => 'above',
'tabLeaveSpace' => true,
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'v1',
'dashType' => 7,
'dashName' => 'v1_snippet2',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'file' => 'Processed.png' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'mp_tmail_snippet5',
'headerBg' => '',
'headerColor' => '#a3a3a3',
'bodyBg' => '#fbfbfb',
'bodyColor' => null,
'panelBorder' => '3px',
'borderColor' => '#fbfbfb',
'snippetStyle' => 'right',
'iconColor' => '#E1A730',
'tabLeaveSpace' => true ),
'elementName' => 'v1_snippet2',
'table' => 'v1',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'mp_tmail_snippet5',
'masterTable' => '',
'tabLocation' => 'above',
'tabLeaveSpace' => true,
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'sp_notif_t_mail',
'dashType' => 0,
'dashName' => 'sp_notif_t_mail_grid',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Notifications' ),
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'height' => '300px',
'customCSS' => '/* Put  your custom CSS code here */

.alert-danger {
    background-color: #e8e2e3;
    border-color: #f0005e;
    color: #fff;
}' ),
'elementName' => 'sp_notif_t_mail_grid',
'table' => 'sp_notif_t_mail',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'c_out_mail',
'dashType' => 1,
'dashName' => 'c_out_mail_chart',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '300px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Out Mail Statistics' ),
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'customCSS' => '/* Put  your custom CSS code here */
.alert-danger {
    background-color: #e8e2e3;
    border-color: #f0005e;
    color: #fff;
}' ),
'elementName' => 'c_out_mail_chart',
'table' => 'c_out_mail',
'type' => 1,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 't_delivery_view',
'dashType' => 1,
'dashName' => 't_delivery_view_chart',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '300px',
'reloadInterval' => 60,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'In Mail Statistics' ),
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'customCSS' => '/* Put  your custom CSS code here */

.alert-danger {
    background-color: #e8e2e3;
    border-color: #f0005e;
    color: #fff;
}' ),
'elementName' => 't_delivery_view_chart',
'table' => 't_delivery_view',
'type' => 1,
'reload' => 60,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'v1',
'dashType' => 7,
'dashName' => 'v1_snippet3',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'fa' => 'gift' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'mp_tmail_snippet9',
'headerBg' => '',
'headerColor' => '#a3a3a3',
'bodyBg' => '#fbfbfb',
'bodyColor' => null,
'panelBorder' => '3px',
'borderColor' => '#fbfbfb',
'height' => '300px' ),
'elementName' => 'v1_snippet3',
'table' => 'v1',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'mp_tmail_snippet9',
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 't_delivery_feedback_view1',
'dashType' => 0,
'dashName' => 't_delivery_feedback_view1_grid',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'fa' => 'motorcycle' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '452px',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Courier Activity' ),
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '#f5f5f5',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'reloadInterval' => 60,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'customCSS' => '
.alert-warning {
    background-color: #e8e2e3;
    border-color: #f0005e;
    color: #fff;
}' ),
'elementName' => 't_delivery_feedback_view1_grid',
'table' => 't_delivery_feedback_view1',
'type' => 0,
'reload' => 60,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 't_delivery_feedback_view',
'dashType' => 6,
'dashName' => 't_delivery_feedback_view_map',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'fa' => 'map' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => false,
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'mapAutoZoom' => true,
'mapLatField' => 't_delivery_feedback_lat',
'mapLonField' => 't_delivery_feedback_log',
'mapDescField' => 'description',
'mapMarkerIcon' => 't_delivery_feedback_view_map_markericon',
'mapMarkerIconCode' => true,
'mapShowLocation' => true,
'mapLocationIcon' => 't_delivery_feedback_view_map_locationicon',
'mapLocationIconCode' => true,
'customLabel' => true,
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '#f5f5f5',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'dashLabel' => array( 'type' => 0,
'text' => 'Tracker your outmail real-time' ) ),
'elementName' => 't_delivery_feedback_view_map',
'table' => 't_delivery_feedback_view',
'type' => 6,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'auto',
'latF' => 't_delivery_feedback_lat',
'lonF' => 't_delivery_feedback_log',
'descF' => 'description',
'isMarkerIconCustom' => true,
'iconF' => 't_delivery_feedback_view_map_markericon',
'updateMoved' => false,
'isLocationMarkerIconCustom' => true,
'showCurrentLocation' => true,
'currentLocationIcon' => 't_delivery_feedback_view_map_locationicon',
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ) ) ),
'dashSearch' => array( 'searchFields' => array( 't_delivery_view_status' => array( array( 'field' => 'status',
'table' => 't_delivery_view' ) ),
't_delivery_view_t_register_status' => array( array( 'field' => 't_register_status',
'table' => 't_delivery_view' ) ),
'c_out_mail_status' => array( array( 'field' => 'status',
'table' => 'c_out_mail' ) ),
'c_out_mail_t_delivery_id' => array( array( 'field' => 't_delivery_id',
'table' => 'c_out_mail' ) ),
'sp_notif_t_mail_kodeuser' => array( array( 'field' => 'kodeuser',
'table' => 'sp_notif_t_mail' ) ),
'sp_notif_t_mail_nama' => array( array( 'field' => 'nama',
'table' => 'sp_notif_t_mail' ) ),
'sp_notif_t_mail_id' => array( array( 'field' => 'id',
'table' => 'sp_notif_t_mail' ) ),
'sp_notif_t_mail_message' => array( array( 'field' => 'message',
'table' => 'sp_notif_t_mail' ) ),
'sp_notif_t_mail_user' => array( array( 'field' => 'user',
'table' => 'sp_notif_t_mail' ) ),
'sp_notif_t_mail_provider' => array( array( 'field' => 'provider',
'table' => 'sp_notif_t_mail' ) ),
'sp_notif_t_mail_title' => array( array( 'field' => 'title',
'table' => 'sp_notif_t_mail' ) ),
'sp_notif_t_mail_url' => array( array( 'field' => 'url',
'table' => 'sp_notif_t_mail' ) ),
'sp_notif_t_mail_icon' => array( array( 'field' => 'icon',
'table' => 'sp_notif_t_mail' ) ),
'sp_notif_t_mail_created' => array( array( 'field' => 'created',
'table' => 'sp_notif_t_mail' ) ),
'sp_notif_t_mail_expire' => array( array( 'field' => 'expire',
'table' => 'sp_notif_t_mail' ) ),
'sp_notif_t_mail_type' => array( array( 'field' => 'type',
'table' => 'sp_notif_t_mail' ) ),
'sp_notif_t_mail_group' => array( array( 'field' => 'group',
'table' => 'sp_notif_t_mail' ) ),
't_delivery_feedback_view_t_delivery_feedback_id' => array( array( 'field' => 't_delivery_feedback_id',
'table' => 't_delivery_feedback_view' ) ),
't_delivery_feedback_view_t_delivery_id' => array( array( 'field' => 't_delivery_id',
'table' => 't_delivery_feedback_view' ) ),
't_delivery_feedback_view_t_delivery_feedback' => array( array( 'field' => 't_delivery_feedback',
'table' => 't_delivery_feedback_view' ) ),
't_delivery_feedback_view_t_delivery_feedback_images' => array( array( 'field' => 't_delivery_feedback_images',
'table' => 't_delivery_feedback_view' ) ),
't_delivery_feedback_view_t_delivery_feedback_sign' => array( array( 'field' => 't_delivery_feedback_sign',
'table' => 't_delivery_feedback_view' ) ),
't_delivery_feedback_view_t_delivery_feedback_log' => array( array( 'field' => 't_delivery_feedback_log',
'table' => 't_delivery_feedback_view' ) ),
't_delivery_feedback_view_t_delivery_feedback_lat' => array( array( 'field' => 't_delivery_feedback_lat',
'table' => 't_delivery_feedback_view' ) ),
't_delivery_feedback_view_add_user' => array( array( 'field' => 'add_user',
'table' => 't_delivery_feedback_view' ) ),
't_delivery_feedback_view_add_date' => array( array( 'field' => 'add_date',
'table' => 't_delivery_feedback_view' ) ),
't_delivery_feedback_view_Lat' => array( array( 'field' => 'Lat',
'table' => 't_delivery_feedback_view' ) ),
't_delivery_feedback_view_Lng' => array( array( 'field' => 'Lng',
'table' => 't_delivery_feedback_view' ) ),
't_delivery_feedback_view_t_delivery_no' => array( array( 'field' => 't_delivery_no',
'table' => 't_delivery_feedback_view' ) ),
't_delivery_feedback_view_usercreate' => array( array( 'field' => 'usercreate',
'table' => 't_delivery_feedback_view' ) ),
't_delivery_feedback_view_description' => array( array( 'field' => 'description',
'table' => 't_delivery_feedback_view' ) ),
't_delivery_feedback_view1_t_delivery_feedback_id' => array( array( 'field' => 't_delivery_feedback_id',
'table' => 't_delivery_feedback_view1' ) ),
't_delivery_feedback_view1_t_delivery_id' => array( array( 'field' => 't_delivery_id',
'table' => 't_delivery_feedback_view1' ) ),
't_delivery_feedback_view1_t_delivery_feedback' => array( array( 'field' => 't_delivery_feedback',
'table' => 't_delivery_feedback_view1' ) ),
't_delivery_feedback_view1_t_delivery_feedback_images' => array( array( 'field' => 't_delivery_feedback_images',
'table' => 't_delivery_feedback_view1' ) ),
't_delivery_feedback_view1_t_delivery_feedback_sign' => array( array( 'field' => 't_delivery_feedback_sign',
'table' => 't_delivery_feedback_view1' ) ),
't_delivery_feedback_view1_t_delivery_feedback_log' => array( array( 'field' => 't_delivery_feedback_log',
'table' => 't_delivery_feedback_view1' ) ),
't_delivery_feedback_view1_t_delivery_feedback_lat' => array( array( 'field' => 't_delivery_feedback_lat',
'table' => 't_delivery_feedback_view1' ) ),
't_delivery_feedback_view1_add_user' => array( array( 'field' => 'add_user',
'table' => 't_delivery_feedback_view1' ) ),
't_delivery_feedback_view1_add_date' => array( array( 'field' => 'add_date',
'table' => 't_delivery_feedback_view1' ) ),
't_delivery_feedback_view1_Lat' => array( array( 'field' => 'Lat',
'table' => 't_delivery_feedback_view1' ) ),
't_delivery_feedback_view1_Lng' => array( array( 'field' => 'Lng',
'table' => 't_delivery_feedback_view1' ) ),
't_delivery_feedback_view1_t_delivery_no' => array( array( 'field' => 't_delivery_no',
'table' => 't_delivery_feedback_view1' ) ),
't_delivery_feedback_view1_t_delivery_date' => array( array( 'field' => 't_delivery_date',
'table' => 't_delivery_feedback_view1' ) ),
't_delivery_feedback_view1_t_delivery_address' => array( array( 'field' => 't_delivery_address',
'table' => 't_delivery_feedback_view1' ) ) ),
'allSearchFields' => array( 't_delivery_view_status',
't_delivery_view_t_register_status',
'c_out_mail_status',
'c_out_mail_t_delivery_id',
'sp_notif_t_mail_kodeuser',
'sp_notif_t_mail_nama',
'sp_notif_t_mail_id',
'sp_notif_t_mail_message',
'sp_notif_t_mail_user',
'sp_notif_t_mail_provider',
'sp_notif_t_mail_title',
'sp_notif_t_mail_url',
'sp_notif_t_mail_icon',
'sp_notif_t_mail_created',
'sp_notif_t_mail_expire',
'sp_notif_t_mail_type',
'sp_notif_t_mail_group',
't_delivery_feedback_view_t_delivery_feedback_id',
't_delivery_feedback_view_t_delivery_id',
't_delivery_feedback_view_t_delivery_feedback',
't_delivery_feedback_view_t_delivery_feedback_images',
't_delivery_feedback_view_t_delivery_feedback_sign',
't_delivery_feedback_view_t_delivery_feedback_log',
't_delivery_feedback_view_t_delivery_feedback_lat',
't_delivery_feedback_view_add_user',
't_delivery_feedback_view_add_date',
't_delivery_feedback_view_Lat',
't_delivery_feedback_view_Lng',
't_delivery_feedback_view_t_delivery_no',
't_delivery_feedback_view_usercreate',
't_delivery_feedback_view_description',
't_delivery_feedback_view1_t_delivery_feedback_id',
't_delivery_feedback_view1_t_delivery_id',
't_delivery_feedback_view1_t_delivery_feedback',
't_delivery_feedback_view1_t_delivery_feedback_images',
't_delivery_feedback_view1_t_delivery_feedback_sign',
't_delivery_feedback_view1_t_delivery_feedback_log',
't_delivery_feedback_view1_t_delivery_feedback_lat',
't_delivery_feedback_view1_add_user',
't_delivery_feedback_view1_add_date',
't_delivery_feedback_view1_Lat',
't_delivery_feedback_view1_Lng',
't_delivery_feedback_view1_t_delivery_no',
't_delivery_feedback_view1_t_delivery_date',
't_delivery_feedback_view1_t_delivery_address' ),
'googleLikeFields' => array( 't_delivery_view_status' ) ) );
			$pageArray = array( 'id' => 'dashboard',
'type' => 'dashboard',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'grid' => array( 'modelId' => 'dashboard-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 1 ),
array( 'cell' => 'c1' ),
array( 'cell' => 'c18' ),
array( 'cell' => 'c13' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c23' ),
array( 'cell' => 'c24' ),
array( 'cell' => 'c25' ),
array( 'cell' => 'c26' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10',
'colspan' => 2 ),
array( 'cell' => 'c22',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'dashboard-item' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'dashboard-item9' ),
'width' => '' ),
'c1' => array( 'model' => 'c1',
'items' => array( 'dashboard-item1' ) ),
'c13' => array( 'model' => 'c1',
'items' => array( 'dashboard-item8' ) ),
'c18' => array( 'model' => 'c1',
'items' => array( 'dashboard-item2' ) ),
'c22' => array( 'model' => 'c1',
'items' => array( 'dashboard-item6' ),
'width' => '' ),
'c23' => array( 'model' => 'c1',
'items' => array( 'dashboard-item5' ),
'width' => '' ),
'c24' => array( 'model' => 'c1',
'items' => array( 'dashboard-item7' ) ),
'c25' => array( 'model' => 'c1',
'items' => array( 'dashboard-item3' ),
'width' => '' ),
'c26' => array( 'model' => 'c1',
'items' => array( 'dashboard-item4' ),
'width' => '' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'notifications',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'dashboard-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c4' => array( 'model' => 'c4',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'notifications' => array( 'type' => 'notifications' ),
'dashboard-item' => array( 'type' => 'dashboard-item',
'table' => 'v1',
'dashType' => 7,
'dashName' => 'v1_snippet',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'file' => 'Out Mail.png' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'mp_tmail_snippet3',
'snippetStyle' => 'right',
'headerColor' => '#a3a3a3',
'bodyBg' => '#fbfbfb',
'bodyColor' => null,
'iconColor' => '#E1A730',
'panelBorder' => '3px',
'borderColor' => '#fbfbfb',
'tabLeaveSpace' => true ),
'dashboard-item1' => array( 'type' => 'dashboard-item',
'table' => 'v1',
'dashType' => 7,
'dashName' => 'v1_snippet1',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'file' => 'In Mail.png' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'mp_tmail_snippet4',
'snippetStyle' => 'right',
'headerColor' => '#a3a3a3',
'bodyBg' => '#fbfbfb',
'bodyColor' => null,
'iconColor' => '#E1A730',
'panelBorder' => '3px',
'borderColor' => '#fbfbfb',
'tabLeaveSpace' => true ),
'dashboard-item2' => array( 'type' => 'dashboard-item',
'table' => 'v1',
'dashType' => 7,
'dashName' => 'v1_snippet2',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'file' => 'Processed.png' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'mp_tmail_snippet5',
'headerBg' => '',
'headerColor' => '#a3a3a3',
'bodyBg' => '#fbfbfb',
'bodyColor' => null,
'panelBorder' => '3px',
'borderColor' => '#fbfbfb',
'snippetStyle' => 'left',
'iconColor' => '#E1A730',
'tabLeaveSpace' => true ),
'dashboard-item3' => array( 'type' => 'dashboard-item',
'table' => 't_delivery_view',
'dashType' => 1,
'dashName' => 't_delivery_view_chart',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '300px',
'reloadInterval' => 60,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'In Mail Statistics' ),
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'customCSS' => '/* Put  your custom CSS code here */

.alert-danger {
    background-color: #e8e2e3;
    border-color: #f0005e;
    color: #fff;
}' ),
'dashboard-item6' => array( 'type' => 'dashboard-item',
'table' => 't_delivery_feedback_view',
'dashType' => 6,
'dashName' => 't_delivery_feedback_view_map',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'fa' => 'map' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => false,
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'mapAutoZoom' => true,
'mapLatField' => 't_delivery_feedback_lat',
'mapLonField' => 't_delivery_feedback_log',
'mapDescField' => 'description',
'mapMarkerIcon' => 't_delivery_feedback_view_map_markericon',
'mapMarkerIconCode' => true,
'mapShowLocation' => true,
'mapLocationIcon' => 't_delivery_feedback_view_map_locationicon',
'mapLocationIconCode' => true,
'customLabel' => true,
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '#f5f5f5',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'dashLabel' => array( 'type' => 0,
'text' => 'Tracker your outmail real-time' ) ),
'dashboard-item7' => array( 'type' => 'dashboard-item',
'table' => 'c_out_mail',
'dashType' => 1,
'dashName' => 'c_out_mail_chart',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '300px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Out Mail Statistics' ),
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'customCSS' => '/* Put  your custom CSS code here */
.alert-danger {
    background-color: #e8e2e3;
    border-color: #f0005e;
    color: #fff;
}' ),
'dashboard-item4' => array( 'type' => 'dashboard-item',
'table' => 'v1',
'dashType' => 7,
'dashName' => 'v1_snippet3',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'fa' => 'gift' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'mp_tmail_snippet9',
'headerBg' => '',
'headerColor' => '#a3a3a3',
'bodyBg' => '#fbfbfb',
'bodyColor' => null,
'panelBorder' => '3px',
'borderColor' => '#fbfbfb',
'height' => '300px' ),
'dashboard-item5' => array( 'type' => 'dashboard-item',
'table' => 'sp_notif_t_mail',
'dashType' => 0,
'dashName' => 'sp_notif_t_mail_grid',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Notifications' ),
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'height' => '300px',
'customCSS' => '/* Put  your custom CSS code here */

.alert-danger {
    background-color: #e8e2e3;
    border-color: #f0005e;
    color: #fff;
}' ),
'dashboard-item8' => array( 'type' => 'dashboard-item',
'table' => 'v1',
'dashType' => 7,
'dashName' => 'v1_snippet2',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'file' => 'Processed.png' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'mp_tmail_snippet5',
'headerBg' => '',
'headerColor' => '#a3a3a3',
'bodyBg' => '#fbfbfb',
'bodyColor' => null,
'panelBorder' => '3px',
'borderColor' => '#fbfbfb',
'snippetStyle' => 'right',
'iconColor' => '#E1A730',
'tabLeaveSpace' => true ),
'dashboard-item9' => array( 'type' => 'dashboard-item',
'table' => 't_delivery_feedback_view1',
'dashType' => 0,
'dashName' => 't_delivery_feedback_view1_grid',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'fa' => 'motorcycle' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '452px',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Courier Activity' ),
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '#f5f5f5',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'reloadInterval' => 60,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'customCSS' => '
.alert-warning {
    background-color: #e8e2e3;
    border-color: #f0005e;
    color: #fff;
}' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'pageCSS' => '/* Put  your custom CSS code here */

[data-itemtype="dashboard-item"].tabelement .panel-heading{
    background: none;
    border: none;
}
[data-itemtype="dashboard-item"].tabelement .panel-heading .rnr-dbebrick{
    color:#337ab7;
}
[data-itemtype="dashboard-item"].tabelement .panel-heading .rnr-dbebrick .btn{
    background: #337AB7;
    color: white;
}
' );
		?>