<?php
			$optionsArray = array( 'totals' => array( 't_delivery_id' => array( 'totalsType' => '' ),
't_delivery_token' => array( 'totalsType' => '' ),
't_delivery_no' => array( 'totalsType' => '' ),
't_delivery_date' => array( 'totalsType' => '' ),
't_delivery_type' => array( 'totalsType' => '' ),
't_location_id' => array( 'totalsType' => '' ),
't_select_table_text' => array( 'totalsType' => '' ),
't_delivery_to_table' => array( 'totalsType' => '' ),
't_delivery_to_text' => array( 'totalsType' => '' ),
't_delivery_address' => array( 'totalsType' => '' ),
't_delivery_desc' => array( 'totalsType' => '' ),
't_delivery_status' => array( 'totalsType' => '' ),
'add_user' => array( 'totalsType' => '' ),
'add_date' => array( 'totalsType' => '' ),
'edit_user' => array( 'totalsType' => '' ),
'edit_date' => array( 'totalsType' => '' ),
'process_user' => array( 'totalsType' => '' ),
'process_date' => array( 'totalsType' => '' ),
'kepada' => array( 'totalsType' => '' ),
't_delivery_category_code' => array( 'totalsType' => '' ),
'last_user' => array( 'totalsType' => '' ),
'last_date' => array( 'totalsType' => '' ),
't_delivery_location_address' => array( 'totalsType' => '' ),
'status' => array( 'totalsType' => '' ),
'fullname' => array( 'totalsType' => '' ),
'm_location_name' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 't_delivery_id',
't_delivery_token',
't_delivery_no',
't_delivery_date',
't_delivery_type',
't_location_id',
't_select_table_text',
't_delivery_to_table',
't_delivery_to_text',
't_delivery_address',
't_delivery_desc',
't_delivery_status',
'add_user',
'add_date',
'edit_user',
'edit_date',
'process_user',
'process_date',
'kepada',
't_delivery_category_code',
'last_user',
'last_date',
't_delivery_location_address',
'status',
'fullname',
'm_location_name' ),
'exportFields' => array( 't_delivery_no',
't_delivery_date',
't_delivery_type',
't_delivery_id',
't_delivery_token',
't_location_id',
't_select_table_text',
't_delivery_to_table',
't_delivery_to_text',
't_delivery_address',
't_delivery_desc',
't_delivery_status',
'add_user',
'add_date',
'edit_user',
'edit_date',
'process_user',
'process_date',
'kepada',
't_delivery_category_code',
'last_user',
'last_date',
't_delivery_location_address',
'status',
'fullname',
'm_location_name' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 't_delivery_id' => array( 'export_field' ),
't_delivery_token' => array( 'export_field1' ),
't_delivery_no' => array( 'export_field2' ),
't_delivery_date' => array( 'export_field3' ),
't_delivery_type' => array( 'export_field4' ),
't_location_id' => array( 'export_field5' ),
't_select_table_text' => array( 'export_field6' ),
't_delivery_to_table' => array( 'export_field7' ),
't_delivery_to_text' => array( 'export_field8' ),
't_delivery_address' => array( 'export_field9' ),
't_delivery_desc' => array( 'export_field10' ),
't_delivery_status' => array( 'export_field11' ),
'add_user' => array( 'export_field12' ),
'add_date' => array( 'export_field13' ),
'edit_user' => array( 'export_field14' ),
'edit_date' => array( 'export_field15' ),
'process_user' => array( 'export_field16' ),
'process_date' => array( 'export_field17' ),
'kepada' => array( 'export_field18' ),
't_delivery_category_code' => array( 'export_field19' ),
'last_user' => array( 'export_field20' ),
'last_date' => array( 'export_field21' ),
't_delivery_location_address' => array( 'export_field22' ),
'status' => array( 'export_field23' ),
'fullname' => array( 'export_field24' ),
'm_location_name' => array( 'export_field25' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field2',
'export_field3',
'export_field4',
'export_field',
'export_field1',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field2',
'export_field3',
'export_field4',
'export_field',
'export_field1',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 't_delivery_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 't_delivery_token',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 't_delivery_no',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 't_delivery_date',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 't_delivery_type',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 't_location_id',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 't_select_table_text',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 't_delivery_to_table',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 't_delivery_to_text',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 't_delivery_address',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 't_delivery_desc',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 't_delivery_status',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'add_user',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'add_date',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'edit_user',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'edit_date',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'process_user',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'process_date',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'kepada',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 't_delivery_category_code',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'last_user',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'last_date',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 't_delivery_location_address',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'status',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'fullname',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'm_location_name',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>