<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'details' => array( 't_delivery_details' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'm_disposition_inmail' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
't_delivery_internal_view' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
't_delivery_expedition_view' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
't_delivery_feedback' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ) ),
'fields' => array( 'gridFields' => array( 'add_user',
't_delivery_no',
't_delivery_date',
't_delivery_type',
't_location_id',
't_select_table_text',
't_delivery_to_table',
't_delivery_to_text',
't_delivery_address',
't_delivery_desc',
't_delivery_status',
'add_date',
'edit_date',
'edit_user',
't_delivery_location_address',
'status_disposition' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'add_user' => array( 'integrated_edit_field' ),
't_delivery_no' => array( 'integrated_edit_field1' ),
't_delivery_date' => array( 'integrated_edit_field2' ),
't_delivery_type' => array( 'integrated_edit_field3' ),
't_location_id' => array( 'integrated_edit_field4' ),
't_select_table_text' => array( 'integrated_edit_field5' ),
't_delivery_to_table' => array( 'integrated_edit_field6' ),
't_delivery_to_text' => array( 'integrated_edit_field7' ),
't_delivery_address' => array( 'integrated_edit_field8' ),
't_delivery_desc' => array( 'integrated_edit_field9' ),
't_delivery_status' => array( 'integrated_edit_field10' ),
'add_date' => array( 'integrated_edit_field11' ),
'edit_date' => array( 'integrated_edit_field12' ),
'edit_user' => array( 'integrated_edit_field13' ),
't_delivery_location_address' => array( 'integrated_edit_field14' ),
'status_disposition' => array( 'integrated_edit_field15' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'custom_button1',
'view_close' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'notifications',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array(  ),
'grid' => array( 'section',
'integrated_edit_field15' ),
'section' => array( 'section3',
'section4',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field',
'integrated_edit_field11',
'integrated_edit_field13',
'integrated_edit_field12',
'section1',
'section2',
'section5' ),
'section1' => array( 'details_preview' ),
'section2' => array( 'details_preview1' ),
'section3' => array( 'integrated_edit_field4',
'integrated_edit_field14' ),
'section4' => array( 'integrated_edit_field5',
'integrated_edit_field8',
'integrated_edit_field6',
'integrated_edit_field7' ),
'section5' => array( 'details_preview2',
'details_preview3',
'details_preview4' ) ),
'formXtTags' => array( 'above-grid' => array(  ),
'top' => array(  ) ),
'itemForms' => array( 'view_back_list' => 'below-grid',
'custom_button1' => 'below-grid',
'view_close' => 'below-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'section' => 'grid',
'integrated_edit_field15' => 'grid',
'section3' => 'section',
'section4' => 'section',
'integrated_edit_field1' => 'section',
'integrated_edit_field2' => 'section',
'integrated_edit_field3' => 'section',
'integrated_edit_field9' => 'section',
'integrated_edit_field10' => 'section',
'integrated_edit_field' => 'section',
'integrated_edit_field11' => 'section',
'integrated_edit_field13' => 'section',
'integrated_edit_field12' => 'section',
'section1' => 'section',
'section2' => 'section',
'section5' => 'section',
'details_preview' => 'section1',
'details_preview1' => 'section2',
'integrated_edit_field4' => 'section3',
'integrated_edit_field14' => 'section3',
'integrated_edit_field5' => 'section4',
'integrated_edit_field8' => 'section4',
'integrated_edit_field6' => 'section4',
'integrated_edit_field7' => 'section4',
'details_preview2' => 'section5',
'details_preview3' => 'section5',
'details_preview4' => 'section5' ),
'itemLocations' => array( 'section' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section3' => array( 'location' => 'section',
'cellId' => 'c5' ),
'section4' => array( 'location' => 'section',
'cellId' => 'c5' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field2' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field3' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field9' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field10' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field11' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field13' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field12' => array( 'location' => 'section',
'cellId' => 'c8' ),
'section1' => array( 'location' => 'section',
'cellId' => 'c11' ),
'section2' => array( 'location' => 'section',
'cellId' => 'c12' ),
'section5' => array( 'location' => 'section',
'cellId' => 'c13' ),
'details_preview' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'details_preview1' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field4' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field14' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field5' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field8' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field6' => array( 'location' => 'section4',
'cellId' => 'c2' ),
'integrated_edit_field7' => array( 'location' => 'section4',
'cellId' => 'c2' ),
'details_preview2' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'details_preview3' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'details_preview4' => array( 'location' => 'section5',
'cellId' => 'c' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'notifications' => array( 'notifications' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15' ),
'details_preview' => array( 'details_preview',
'details_preview1',
'details_preview2',
'details_preview3',
'details_preview4' ),
'section' => array( 'section',
'section1',
'section2',
'section3',
'section4',
'section5' ),
'custom_button' => array( 'custom_button1' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section',
'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c5' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section3',
'section4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field',
'integrated_edit_field11',
'integrated_edit_field13',
'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 0,
1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'section1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 0,
1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'section5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0,
1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'section2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6',
'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 3 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview2',
'details_preview3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'details_preview4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => true,
'customButtons' => array( 'New_Button1' ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'New_Button1' ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'custom_button1',
'view_close' ) ),
'c2' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'notifications',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'section',
'integrated_edit_field15' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c5',
'colspan' => 1 ),
array( 'cell' => 'c8',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c11',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c13',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c5' => array( 'model' => 'c1',
'items' => array( 'section3',
'section4' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field',
'integrated_edit_field11',
'integrated_edit_field13',
'integrated_edit_field12' ) ),
'c11' => array( 'model' => 'c1',
'items' => array( 'section1' ) ),
'c12' => array( 'model' => 'c1',
'items' => array( 'section2' ) ),
'c13' => array( 'model' => 'c1',
'items' => array( 'section5' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview1' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field14' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6',
'integrated_edit_field7' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview2',
'details_preview3' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'details_preview4' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_back_list' => array( 'type' => 'view_back_list',
'width' => '100px',
'icon' => array( 'fa' => 'th-list' ) ),
'view_close' => array( 'type' => 'view_close' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'notifications' => array( 'type' => 'notifications' ),
'integrated_edit_field' => array( 'field' => 'add_user',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 't_delivery_no',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field2' => array( 'field' => 't_delivery_date',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field3' => array( 'field' => 't_delivery_type',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field4' => array( 'field' => 't_location_id',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field5' => array( 'field' => 't_select_table_text',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field6' => array( 'field' => 't_delivery_to_table',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field7' => array( 'field' => 't_delivery_to_text',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 't_delivery_address',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 't_delivery_desc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 't_delivery_status',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field11' => array( 'field' => 'add_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'edit_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'edit_user',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 't_delivery_details',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'section' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Out Mail, View' ),
'location' => 'section',
'bsStyle' => 'default',
'panelType' => 3 ),
'section1' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Detail Parameter' ),
'location' => 'section1',
'bsStyle' => 'default',
'panelType' => 3 ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'm_disposition_inmail',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'section2' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Disposition' ),
'location' => 'section2',
'bsStyle' => 'default',
'panelType' => 3 ),
'custom_button1' => array( 'eventId' => 'New_Button1',
'label' => array( 'text' => 'Print',
'type' => 0 ),
'type' => 'custom_button',
'width' => '100px',
'icon' => array( 'fa' => 'print' ) ),
'details_preview2' => array( 'type' => 'details_preview',
'table' => 't_delivery_internal_view',
'items' => array(  ),
'popup' => false,
'pageId' => 'list',
'caption' => array( 'page' => 'list',
'table' => 't_delivery_internal_view',
'type' => 7 ) ),
'details_preview3' => array( 'type' => 'details_preview',
'table' => 't_delivery_expedition_view',
'items' => array(  ),
'popup' => false,
'pageId' => 'list',
'caption' => array( 'page' => 'list',
'table' => 't_delivery_expedition_view',
'type' => 7 ) ),
'details_preview4' => array( 'type' => 'details_preview',
'table' => 't_delivery_feedback',
'items' => array(  ),
'popup' => false,
'pageId' => 'list',
'caption' => array( 'page' => 'list',
'table' => 't_delivery_feedback',
'type' => 7 ) ),
'section3' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Origin' ),
'location' => 'section3',
'bsStyle' => 'default',
'panelType' => 3 ),
'integrated_edit_field14' => array( 'field' => 't_delivery_location_address',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section4' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Destination' ),
'location' => 'section4',
'bsStyle' => 'default',
'panelType' => 3 ),
'section5' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Activity' ),
'location' => 'section5',
'bsStyle' => 'default',
'panelType' => 3 ),
'integrated_edit_field15' => array( 'field' => 'status_disposition',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'pageWidth' => 'full',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>