<?php
			$optionsArray = array( 'details' => array( 't_delivery_details' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'm_disposition_inmail' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
't_delivery_internal_view' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
't_delivery_expedition_view' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
't_delivery_feedback' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 't_location_id',
't_delivery_location_address',
't_select_table_text',
't_delivery_address',
't_delivery_to_text',
't_delivery_to_table',
't_delivery_no',
't_delivery_date',
't_delivery_type',
't_delivery_desc',
't_delivery_status',
'add_user' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 't_location_id' => array( 'integrated_edit_field4' ),
't_delivery_location_address' => array( 'integrated_edit_field' ),
't_select_table_text' => array( 'integrated_edit_field5' ),
't_delivery_address' => array( 'integrated_edit_field8' ),
't_delivery_to_text' => array( 'integrated_edit_field7' ),
't_delivery_to_table' => array( 'integrated_edit_field6' ),
't_delivery_no' => array( 'integrated_edit_field1' ),
't_delivery_date' => array( 'integrated_edit_field2' ),
't_delivery_type' => array( 'integrated_edit_field3' ),
't_delivery_desc' => array( 'integrated_edit_field9' ),
't_delivery_status' => array( 'integrated_edit_field10' ),
'add_user' => array( 'integrated_edit_field11' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'add_message',
'adminarea_link',
'changepassword_link',
'notifications' ),
'below-grid' => array( 'add_save',
'add_reset',
'add_back_list',
'add_cancel' ),
'top' => array(  ),
'grid' => array( 'section' ),
'section' => array( 'section2',
'section1',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11' ),
'section2' => array( 'integrated_edit_field4',
'integrated_edit_field' ),
'section1' => array( 'integrated_edit_field5',
'integrated_edit_field8',
'integrated_edit_field7',
'integrated_edit_field6' ) ),
'formXtTags' => array( 'top' => array(  ) ),
'itemForms' => array( 'add_message' => 'above-grid',
'adminarea_link' => 'above-grid',
'changepassword_link' => 'above-grid',
'notifications' => 'above-grid',
'add_save' => 'below-grid',
'add_reset' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'section' => 'grid',
'section2' => 'section',
'section1' => 'section',
'integrated_edit_field1' => 'section',
'integrated_edit_field2' => 'section',
'integrated_edit_field3' => 'section',
'integrated_edit_field9' => 'section',
'integrated_edit_field10' => 'section',
'integrated_edit_field11' => 'section',
'integrated_edit_field4' => 'section2',
'integrated_edit_field' => 'section2',
'integrated_edit_field5' => 'section1',
'integrated_edit_field8' => 'section1',
'integrated_edit_field7' => 'section1',
'integrated_edit_field6' => 'section1' ),
'itemLocations' => array( 'section' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section2' => array( 'location' => 'section',
'cellId' => 'c1' ),
'section1' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field2' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field3' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field9' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field10' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field11' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field4' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field5' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field8' => array( 'location' => 'section1',
'cellId' => 'c2' ),
'integrated_edit_field7' => array( 'location' => 'section1',
'cellId' => 'c3' ),
'integrated_edit_field6' => array( 'location' => 'section1',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'add_reset' => array( 'add_reset' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'section' => array( 'section',
'section2',
'section1' ),
'integrated_edit_field' => array( 'integrated_edit_field4',
'integrated_edit_field',
'integrated_edit_field5',
'integrated_edit_field8',
'integrated_edit_field7',
'integrated_edit_field6',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'notifications' => array( 'notifications' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section2',
'section1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7',
'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'adminarea_link',
'changepassword_link',
'notifications' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_reset',
'add_back_list',
'add_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'section' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'rowspan' => 1 ),
array( 'cell' => 'c3',
'rowspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'section2',
'section1' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2',
'colspan' => 1 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ),
'useFullWidth' => true ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7',
'integrated_edit_field6' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save',
'icon' => array( 'fa' => 'save' ),
'width' => '100px',
'customCSS' => '.btn-primary {
    color: #fff;
    background-color: #BC9C22;
    border-color: transparent;
}
.btn-primary:hover, .btn-primary:focus, .btn-group.open .dropdown-toggle.btn-primary {
    background-color: #e7c235;
    border-color: #b6a35d;
}' ),
'add_reset' => array( 'type' => 'add_reset',
'icon' => array( 'fa' => 'refresh' ),
'width' => '100px' ),
'add_back_list' => array( 'type' => 'add_back_list',
'icon' => array( 'fa' => 'th-list' ),
'width' => '100px' ),
'add_cancel' => array( 'type' => 'add_cancel',
'icon' => array( 'fa' => 'rotate-left' ) ),
'section' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Out Mail, Add New Form' ),
'location' => 'section',
'bsStyle' => 'default',
'panelType' => 3 ),
'section2' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Origin' ),
'location' => 'section2',
'bsStyle' => 'default',
'panelType' => 3 ),
'integrated_edit_field4' => array( 'field' => 't_location_id',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 't_location_id',
'table' => 't_delivery',
'type' => 3 ) ),
'integrated_edit_field' => array( 'field' => 't_delivery_location_address',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 't_delivery_location_address',
'table' => 't_delivery',
'type' => 3 ) ),
'section1' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Destination' ),
'location' => 'section1',
'bsStyle' => 'default',
'panelType' => 3 ),
'integrated_edit_field5' => array( 'field' => 't_select_table_text',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 't_select_table_text',
'table' => 't_delivery',
'type' => 3 ) ),
'integrated_edit_field8' => array( 'field' => 't_delivery_address',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 't_delivery_to_text',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 't_delivery_to_table',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 't_delivery_no',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 't_delivery_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 't_delivery_type',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 't_delivery_desc',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 't_delivery_desc',
'table' => 't_delivery',
'type' => 3 ) ),
'integrated_edit_field10' => array( 'field' => 't_delivery_status',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'add_user',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'notifications' => array( 'type' => 'notifications' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>