<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 't_delivery_feedback_id',
't_delivery_id',
't_delivery_feedback',
't_delivery_feedback_images',
't_delivery_feedback_sign',
't_delivery_feedback_log',
't_delivery_feedback_lat',
'add_user',
'add_date',
'Lat',
'Lng',
't_delivery_no',
't_delivery_date',
't_delivery_address' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 't_delivery_feedback_id' => array( 'import_field' ),
't_delivery_id' => array( 'import_field1' ),
't_delivery_feedback' => array( 'import_field2' ),
't_delivery_feedback_images' => array( 'import_field3' ),
't_delivery_feedback_sign' => array( 'import_field4' ),
't_delivery_feedback_log' => array( 'import_field5' ),
't_delivery_feedback_lat' => array( 'import_field6' ),
'add_user' => array( 'import_field7' ),
'add_date' => array( 'import_field8' ),
'Lat' => array( 'import_field9' ),
'Lng' => array( 'import_field10' ),
't_delivery_no' => array( 'import_field11' ),
't_delivery_date' => array( 'import_field12' ),
't_delivery_address' => array( 'import_field13' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 't_delivery_feedback_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 't_delivery_id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 't_delivery_feedback',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 't_delivery_feedback_images',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 't_delivery_feedback_sign',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 't_delivery_feedback_log',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 't_delivery_feedback_lat',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'add_user',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'add_date',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'Lat',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'Lng',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 't_delivery_no',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 't_delivery_date',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 't_delivery_address',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>