<?php
			$optionsArray = array( 'totals' => array( 't_invoice_id' => array( 'totalsType' => '' ),
'invoice_no' => array( 'totalsType' => '' ),
'invoice_term' => array( 'totalsType' => '' ),
'invoice_date' => array( 'totalsType' => '' ),
'invoice_type' => array( 'totalsType' => '' ),
'invoice_to' => array( 'totalsType' => '' ),
'invoice_address' => array( 'totalsType' => '' ),
'invoice_mobile_no' => array( 'totalsType' => '' ),
'invoice_email' => array( 'totalsType' => '' ),
'invoice_currency' => array( 'totalsType' => '' ),
'invoice_exchange_rate' => array( 'totalsType' => '' ),
'invoice_original_currency' => array( 'totalsType' => '' ),
'invoice_disc_perc' => array( 'totalsType' => '' ),
'invoice_disc' => array( 'totalsType' => '' ),
'invoice_tax_perc' => array( 'totalsType' => '' ),
'invoice_tax' => array( 'totalsType' => '' ),
'invoice_amount_nett' => array( 'totalsType' => '' ),
'invoice_idr' => array( 'totalsType' => '' ),
'invoice_payment_term' => array( 'totalsType' => '' ),
'invoice_term_days' => array( 'totalsType' => '' ),
'invoice_due_date' => array( 'totalsType' => '' ),
'add_user' => array( 'totalsType' => '' ),
'add_date' => array( 'totalsType' => '' ),
'last_user' => array( 'totalsType' => '' ),
'last_date' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 't_invoice_id',
'invoice_no',
'invoice_date',
'invoice_type',
'invoice_to',
'invoice_address',
'invoice_mobile_no',
'invoice_email',
'invoice_currency',
'invoice_exchange_rate',
'invoice_original_currency',
'invoice_disc',
'invoice_tax',
'invoice_amount_nett',
'invoice_idr',
'invoice_term',
'invoice_disc_perc',
'invoice_tax_perc',
'invoice_term_days',
'invoice_due_date' ),
'exportFields' => array( 't_invoice_id',
'invoice_no',
'invoice_date',
'invoice_type',
'invoice_to',
'invoice_address',
'invoice_mobile_no',
'invoice_email',
'invoice_currency',
'invoice_exchange_rate',
'invoice_original_currency',
'invoice_disc',
'invoice_tax',
'invoice_amount_nett',
'invoice_idr',
'invoice_term',
'invoice_disc_perc',
'invoice_tax_perc',
'invoice_term_days',
'invoice_due_date' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 't_invoice_id' => array( 'export_field' ),
'invoice_no' => array( 'export_field1' ),
'invoice_date' => array( 'export_field2' ),
'invoice_type' => array( 'export_field3' ),
'invoice_to' => array( 'export_field4' ),
'invoice_address' => array( 'export_field5' ),
'invoice_mobile_no' => array( 'export_field6' ),
'invoice_email' => array( 'export_field7' ),
'invoice_currency' => array( 'export_field8' ),
'invoice_exchange_rate' => array( 'export_field9' ),
'invoice_original_currency' => array( 'export_field10' ),
'invoice_disc' => array( 'export_field11' ),
'invoice_tax' => array( 'export_field12' ),
'invoice_amount_nett' => array( 'export_field13' ),
'invoice_idr' => array( 'export_field14' ),
'invoice_term' => array( 'export_field15' ),
'invoice_disc_perc' => array( 'export_field16' ),
'invoice_tax_perc' => array( 'export_field17' ),
'invoice_term_days' => array( 'export_field19' ),
'invoice_due_date' => array( 'export_field20' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field19',
'export_field20' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field19',
'export_field20' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field19',
'export_field20' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 't_invoice_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'invoice_no',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'invoice_date',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'invoice_type',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'invoice_to',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'invoice_address',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'invoice_mobile_no',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'invoice_email',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'invoice_currency',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'invoice_exchange_rate',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'invoice_original_currency',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'invoice_disc',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'invoice_tax',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'invoice_amount_nett',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'invoice_idr',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'invoice_term',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'invoice_disc_perc',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'invoice_tax_perc',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'invoice_term_days',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'invoice_due_date',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>