<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 't_invoice_id',
'invoice_no',
'invoice_date',
'invoice_type',
'invoice_to',
'invoice_address',
'invoice_mobile_no',
'invoice_email',
'invoice_currency',
'invoice_exchange_rate',
'invoice_original_currency',
'invoice_disc',
'invoice_tax',
'invoice_amount_nett',
'invoice_idr',
'invoice_term',
'invoice_disc_perc',
'invoice_tax_perc',
'invoice_term_days',
'invoice_due_date' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 't_invoice_id' => array( 'import_field' ),
'invoice_no' => array( 'import_field1' ),
'invoice_date' => array( 'import_field2' ),
'invoice_type' => array( 'import_field3' ),
'invoice_to' => array( 'import_field4' ),
'invoice_address' => array( 'import_field5' ),
'invoice_mobile_no' => array( 'import_field6' ),
'invoice_email' => array( 'import_field7' ),
'invoice_currency' => array( 'import_field8' ),
'invoice_exchange_rate' => array( 'import_field9' ),
'invoice_original_currency' => array( 'import_field10' ),
'invoice_disc' => array( 'import_field11' ),
'invoice_tax' => array( 'import_field12' ),
'invoice_amount_nett' => array( 'import_field13' ),
'invoice_idr' => array( 'import_field14' ),
'invoice_term' => array( 'import_field15' ),
'invoice_disc_perc' => array( 'import_field16' ),
'invoice_tax_perc' => array( 'import_field17' ),
'invoice_term_days' => array( 'import_field19' ),
'invoice_due_date' => array( 'import_field20' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field19',
'import_field20' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field19',
'import_field20' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field19',
'import_field20' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 't_invoice_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'invoice_no',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'invoice_date',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'invoice_type',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'invoice_to',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'invoice_address',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'invoice_mobile_no',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'invoice_email',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'invoice_currency',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'invoice_exchange_rate',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'invoice_original_currency',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'invoice_disc',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'invoice_tax',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'invoice_amount_nett',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'invoice_idr',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'invoice_term',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'invoice_disc_perc',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'invoice_tax_perc',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'invoice_term_days',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'invoice_due_date',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>