<?php
			$optionsArray = array( 'details' => array( 't_letter_flow' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 't_letter_no',
'add_user',
'letter_reg_date',
'letter_language',
'letter_signature',
'letter_status',
'm_category_id',
'm_type_id',
'm_template_id',
'letter_perihal',
'letter_kepada',
'letter_attn',
'letter_alamat',
'letter_ttg',
'letter_ttgjwb' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 't_letter_no' => array( 'integrated_edit_field' ),
'add_user' => array( 'integrated_edit_field7' ),
'letter_reg_date' => array( 'integrated_edit_field3' ),
'letter_language' => array( 'integrated_edit_field19' ),
'letter_signature' => array( 'integrated_edit_field20' ),
'letter_status' => array( 'integrated_edit_field15' ),
'm_category_id' => array( 'integrated_edit_field2' ),
'm_type_id' => array( 'integrated_edit_field17' ),
'm_template_id' => array( 'integrated_edit_field18' ),
'letter_perihal' => array( 'integrated_edit_field9' ),
'letter_kepada' => array( 'integrated_edit_field4' ),
'letter_attn' => array( 'integrated_edit_field6' ),
'letter_alamat' => array( 'integrated_edit_field5' ),
'letter_ttg' => array( 'integrated_edit_field10' ),
'letter_ttgjwb' => array( 'integrated_edit_field11' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'add_message',
'adminarea_link',
'changepassword_link',
'notifications' ),
'below-grid' => array( 'add_save',
'add_reset',
'add_back_list',
'add_cancel' ),
'top' => array(  ),
'grid' => array( 'section',
'section1' ),
'section' => array( 'integrated_edit_field',
'integrated_edit_field7',
'integrated_edit_field3',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field15',
'integrated_edit_field2',
'integrated_edit_field17',
'integrated_edit_field18' ),
'section1' => array( 'integrated_edit_field9',
'integrated_edit_field4',
'integrated_edit_field6',
'integrated_edit_field5',
'integrated_edit_field10',
'integrated_edit_field11' ) ),
'formXtTags' => array( 'top' => array(  ) ),
'itemForms' => array( 'add_message' => 'above-grid',
'adminarea_link' => 'above-grid',
'changepassword_link' => 'above-grid',
'notifications' => 'above-grid',
'add_save' => 'below-grid',
'add_reset' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'section' => 'grid',
'section1' => 'grid',
'integrated_edit_field' => 'section',
'integrated_edit_field7' => 'section',
'integrated_edit_field3' => 'section',
'integrated_edit_field19' => 'section',
'integrated_edit_field20' => 'section',
'integrated_edit_field15' => 'section',
'integrated_edit_field2' => 'section',
'integrated_edit_field17' => 'section',
'integrated_edit_field18' => 'section',
'integrated_edit_field9' => 'section1',
'integrated_edit_field4' => 'section1',
'integrated_edit_field6' => 'section1',
'integrated_edit_field5' => 'section1',
'integrated_edit_field10' => 'section1',
'integrated_edit_field11' => 'section1' ),
'itemLocations' => array( 'section' => array( 'location' => 'grid',
'cellId' => 'c' ),
'section1' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_edit_field' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field7' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field3' => array( 'location' => 'section',
'cellId' => 'c2' ),
'integrated_edit_field19' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field20' => array( 'location' => 'section',
'cellId' => 'c4' ),
'integrated_edit_field15' => array( 'location' => 'section',
'cellId' => 'c5' ),
'integrated_edit_field2' => array( 'location' => 'section',
'cellId' => 'c9' ),
'integrated_edit_field17' => array( 'location' => 'section',
'cellId' => 'c10' ),
'integrated_edit_field18' => array( 'location' => 'section',
'cellId' => 'c11' ),
'integrated_edit_field9' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field4' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field6' => array( 'location' => 'section1',
'cellId' => 'c2' ),
'integrated_edit_field5' => array( 'location' => 'section1',
'cellId' => 'c3' ),
'integrated_edit_field10' => array( 'location' => 'section1',
'cellId' => 'c4' ),
'integrated_edit_field11' => array( 'location' => 'section1',
'cellId' => 'c5' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'add_reset' => array( 'add_reset' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'section' => array( 'section',
'section1' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field7',
'integrated_edit_field3',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field15',
'integrated_edit_field2',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field9',
'integrated_edit_field4',
'integrated_edit_field6',
'integrated_edit_field5',
'integrated_edit_field10',
'integrated_edit_field11' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'notifications' => array( 'notifications' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'section1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 3 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'adminarea_link',
'changepassword_link',
'notifications' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_reset',
'add_back_list',
'add_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1' ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c3',
'items' => array( 'section' ),
'useFullWidth' => true ),
'c1' => array( 'model' => 'c3',
'items' => array( 'section1' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9' ),
array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ) ),
'c11' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field18' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save',
'icon' => array( 'fa' => 'save' ) ),
'add_reset' => array( 'type' => 'add_reset',
'icon' => array( 'fa' => 'refresh' ) ),
'add_back_list' => array( 'type' => 'add_back_list',
'icon' => array( 'fa' => 'th-list' ) ),
'add_cancel' => array( 'type' => 'add_cancel',
'icon' => array( 'glyph' => 'repeat' ) ),
'section' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Letter Type Parameter' ),
'location' => 'section',
'bsStyle' => 'default',
'panelType' => 3,
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'panelBorder' => '',
'borderColor' => '' ),
'integrated_edit_field' => array( 'field' => 't_letter_no',
'type' => 'integrated_edit_field',
'orientation' => 1,
'label' => array( 'field' => 't_letter_no',
'table' => 't_letter',
'type' => 3 ) ),
'integrated_edit_field7' => array( 'field' => 'add_user',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field3' => array( 'field' => 'letter_reg_date',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field19' => array( 'field' => 'letter_language',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field20' => array( 'field' => 'letter_signature',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field15' => array( 'field' => 'letter_status',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field2' => array( 'field' => 'm_category_id',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field17' => array( 'field' => 'm_type_id',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field18' => array( 'field' => 'm_template_id',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'section1' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Letter Form' ),
'location' => 'section1',
'bsStyle' => 'default',
'panelType' => 3 ),
'integrated_edit_field9' => array( 'field' => 'letter_perihal',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field4' => array( 'field' => 'letter_kepada',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field6' => array( 'field' => 'letter_attn',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field5' => array( 'field' => 'letter_alamat',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field10' => array( 'field' => 'letter_ttg',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field11' => array( 'field' => 'letter_ttgjwb',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'notifications' => array( 'type' => 'notifications' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>