<?php
			$optionsArray = array( 'totals' => array( 'letter_id' => array( 'totalsType' => '' ),
't_letter_no' => array( 'totalsType' => '' ),
'm_category_code' => array( 'totalsType' => '' ),
'm_category_id' => array( 'totalsType' => '' ),
'letter_reg_date' => array( 'totalsType' => '' ),
'letter_kepada' => array( 'totalsType' => '' ),
'letter_alamat' => array( 'totalsType' => '' ),
'letter_attn' => array( 'totalsType' => '' ),
'add_user' => array( 'totalsType' => '' ),
'add_date' => array( 'totalsType' => '' ),
'letter_perihal' => array( 'totalsType' => '' ),
'letter_ttg' => array( 'totalsType' => '' ),
'letter_ttgjwb' => array( 'totalsType' => '' ),
'letter_kota' => array( 'totalsType' => '' ),
'edit_user' => array( 'totalsType' => '' ),
'edit_date' => array( 'totalsType' => '' ),
'letter_status' => array( 'totalsType' => '' ),
'letter_token' => array( 'totalsType' => '' ),
'm_type_id' => array( 'totalsType' => '' ),
'm_template_id' => array( 'totalsType' => '' ),
'letter_language' => array( 'totalsType' => '' ),
'letter_signature' => array( 'totalsType' => '' ),
'template_file' => array( 'totalsType' => '' ),
'review_file' => array( 'totalsType' => '' ),
'result_file' => array( 'totalsType' => '' ),
'merge_file' => array( 'totalsType' => '' ),
'end_file' => array( 'totalsType' => '' ),
'pdf_file' => array( 'totalsType' => '' ),
'last_user_flow' => array( 'totalsType' => '' ),
'last_user_date' => array( 'totalsType' => '' ),
'qr_sign_text' => array( 'totalsType' => '' ),
'qr_sign_file' => array( 'totalsType' => '' ),
'qr_validation_text' => array( 'totalsType' => '' ),
'qr_validation_file' => array( 'totalsType' => '' ),
'category_no' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'letter_id',
't_letter_no',
'm_category_code',
'm_category_id',
'letter_reg_date',
'letter_kepada',
'letter_alamat',
'letter_attn',
'add_user',
'add_date',
'letter_perihal',
'letter_ttg',
'letter_ttgjwb',
'letter_kota',
'edit_user',
'edit_date',
'letter_status',
'letter_token',
'm_type_id',
'm_template_id',
'letter_language',
'letter_signature',
'template_file',
'review_file',
'result_file',
'merge_file',
'end_file',
'pdf_file',
'last_user_flow',
'last_user_date',
'qr_sign_text',
'qr_sign_file',
'qr_validation_text',
'qr_validation_file',
'category_no' ),
'exportFields' => array( 'letter_id',
't_letter_no',
'm_category_code',
'm_category_id',
'letter_reg_date',
'letter_kepada',
'letter_alamat',
'letter_attn',
'add_user',
'add_date',
'letter_perihal',
'letter_ttg',
'letter_ttgjwb',
'letter_kota',
'edit_user',
'edit_date',
'letter_status',
'letter_token',
'm_type_id',
'm_template_id',
'letter_language',
'letter_signature',
'template_file',
'review_file',
'result_file',
'merge_file',
'end_file',
'pdf_file',
'last_user_flow',
'last_user_date',
'qr_sign_text',
'qr_sign_file',
'qr_validation_text',
'qr_validation_file',
'category_no' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'letter_id' => array( 'export_field' ),
't_letter_no' => array( 'export_field1' ),
'm_category_code' => array( 'export_field2' ),
'm_category_id' => array( 'export_field3' ),
'letter_reg_date' => array( 'export_field4' ),
'letter_kepada' => array( 'export_field5' ),
'letter_alamat' => array( 'export_field6' ),
'letter_attn' => array( 'export_field7' ),
'add_user' => array( 'export_field8' ),
'add_date' => array( 'export_field9' ),
'letter_perihal' => array( 'export_field10' ),
'letter_ttg' => array( 'export_field11' ),
'letter_ttgjwb' => array( 'export_field12' ),
'letter_kota' => array( 'export_field13' ),
'edit_user' => array( 'export_field14' ),
'edit_date' => array( 'export_field15' ),
'letter_status' => array( 'export_field16' ),
'letter_token' => array( 'export_field17' ),
'm_type_id' => array( 'export_field18' ),
'm_template_id' => array( 'export_field19' ),
'letter_language' => array( 'export_field20' ),
'letter_signature' => array( 'export_field21' ),
'template_file' => array( 'export_field22' ),
'review_file' => array( 'export_field23' ),
'result_file' => array( 'export_field24' ),
'merge_file' => array( 'export_field25' ),
'end_file' => array( 'export_field26' ),
'pdf_file' => array( 'export_field27' ),
'last_user_flow' => array( 'export_field28' ),
'last_user_date' => array( 'export_field29' ),
'qr_sign_text' => array( 'export_field30' ),
'qr_sign_file' => array( 'export_field31' ),
'qr_validation_text' => array( 'export_field32' ),
'qr_validation_file' => array( 'export_field33' ),
'category_no' => array( 'export_field34' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'letter_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 't_letter_no',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'm_category_code',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'm_category_id',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'letter_reg_date',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'letter_kepada',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'letter_alamat',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'letter_attn',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'add_user',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'add_date',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'letter_perihal',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'letter_ttg',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'letter_ttgjwb',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'letter_kota',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'edit_user',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'edit_date',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'letter_status',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'letter_token',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'm_type_id',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'm_template_id',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'letter_language',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'letter_signature',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'template_file',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'review_file',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'result_file',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'merge_file',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'end_file',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'pdf_file',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'last_user_flow',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'last_user_date',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'qr_sign_text',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'qr_sign_file',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'qr_validation_text',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'qr_validation_file',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'category_no',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>