<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'letter_id',
't_letter_no',
'm_category_code',
'm_category_id',
'letter_reg_date',
'letter_kepada',
'letter_alamat',
'letter_attn',
'add_user',
'add_date',
'letter_perihal',
'letter_ttg',
'letter_ttgjwb',
'letter_kota',
'edit_user',
'edit_date',
'letter_status',
'letter_token',
'm_type_id',
'm_template_id',
'letter_language',
'letter_signature',
'template_file',
'review_file',
'result_file',
'merge_file',
'end_file',
'pdf_file',
'last_user_flow',
'last_user_date',
'qr_sign_text',
'qr_sign_file',
'qr_validation_text',
'qr_validation_file',
'category_no' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'letter_id' => array( 'import_field' ),
't_letter_no' => array( 'import_field1' ),
'm_category_code' => array( 'import_field2' ),
'm_category_id' => array( 'import_field3' ),
'letter_reg_date' => array( 'import_field4' ),
'letter_kepada' => array( 'import_field5' ),
'letter_alamat' => array( 'import_field6' ),
'letter_attn' => array( 'import_field7' ),
'add_user' => array( 'import_field8' ),
'add_date' => array( 'import_field9' ),
'letter_perihal' => array( 'import_field10' ),
'letter_ttg' => array( 'import_field11' ),
'letter_ttgjwb' => array( 'import_field12' ),
'letter_kota' => array( 'import_field13' ),
'edit_user' => array( 'import_field14' ),
'edit_date' => array( 'import_field15' ),
'letter_status' => array( 'import_field16' ),
'letter_token' => array( 'import_field17' ),
'm_type_id' => array( 'import_field18' ),
'm_template_id' => array( 'import_field19' ),
'letter_language' => array( 'import_field20' ),
'letter_signature' => array( 'import_field21' ),
'template_file' => array( 'import_field22' ),
'review_file' => array( 'import_field23' ),
'result_file' => array( 'import_field24' ),
'merge_file' => array( 'import_field25' ),
'end_file' => array( 'import_field26' ),
'pdf_file' => array( 'import_field27' ),
'last_user_flow' => array( 'import_field28' ),
'last_user_date' => array( 'import_field29' ),
'qr_sign_text' => array( 'import_field30' ),
'qr_sign_file' => array( 'import_field31' ),
'qr_validation_text' => array( 'import_field32' ),
'qr_validation_file' => array( 'import_field33' ),
'category_no' => array( 'import_field34' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'letter_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 't_letter_no',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'm_category_code',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'm_category_id',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'letter_reg_date',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'letter_kepada',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'letter_alamat',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'letter_attn',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'add_user',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'add_date',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'letter_perihal',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'letter_ttg',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'letter_ttgjwb',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'letter_kota',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'edit_user',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'edit_date',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'letter_status',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'letter_token',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'm_type_id',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'm_template_id',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'letter_language',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'letter_signature',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'template_file',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'review_file',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'result_file',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'merge_file',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'end_file',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'pdf_file',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'last_user_flow',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'last_user_date',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'qr_sign_text',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'qr_sign_file',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'qr_validation_text',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'qr_validation_file',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'category_no',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>