<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 't_meeting_id',
't_meeting_roomid',
't_meeting_no',
't_meeting_user',
't_meeting_desc',
't_meeting_from_date',
't_meeting_to_date',
'user_participant_list',
't_meeting_participant_type',
't_meeting_total_participant',
't_meeting_isminuman',
't_meeting_issnack',
't_meeting_ismakan',
't_meeting_recurring_flag',
't_meeting_status',
'fr_date',
'to_dt',
'fr_time',
'to_time',
'meet_approve' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 't_meeting_id' => array( 'import_field' ),
't_meeting_roomid' => array( 'import_field1' ),
't_meeting_no' => array( 'import_field2' ),
't_meeting_user' => array( 'import_field3' ),
't_meeting_desc' => array( 'import_field4' ),
't_meeting_from_date' => array( 'import_field5' ),
't_meeting_to_date' => array( 'import_field6' ),
'fr_date' => array( 'import_field7' ),
'to_dt' => array( 'import_field8' ),
'user_participant_list' => array( 'import_field9' ),
't_meeting_participant_type' => array( 'import_field10' ),
't_meeting_total_participant' => array( 'import_field11' ),
't_meeting_isminuman' => array( 'import_field12' ),
't_meeting_issnack' => array( 'import_field13' ),
't_meeting_ismakan' => array( 'import_field14' ),
't_meeting_recurring_flag' => array( 'import_field15' ),
't_meeting_status' => array( 'import_field16' ),
'fr_time' => array( 'import_field17' ),
'to_time' => array( 'import_field18' ),
'meet_approve' => array( 'import_field19' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field7',
'import_field8',
'import_field17',
'import_field18',
'import_field19' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field7',
'import_field8',
'import_field17',
'import_field18',
'import_field19' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 't_meeting_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 't_meeting_roomid',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 't_meeting_no',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 't_meeting_user',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 't_meeting_desc',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 't_meeting_from_date',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 't_meeting_to_date',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'fr_date',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'to_dt',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'user_participant_list',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 't_meeting_participant_type',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 't_meeting_total_participant',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 't_meeting_isminuman',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 't_meeting_issnack',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 't_meeting_ismakan',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 't_meeting_recurring_flag',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 't_meeting_status',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'fr_time',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'to_time',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'meet_approve',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>