<?php
			$optionsArray = array( 'totals' => array( 't_meeting_id' => array( 'totalsType' => '' ),
't_meeting_roomid' => array( 'totalsType' => '' ),
't_meeting_no' => array( 'totalsType' => '' ),
't_meeting_user' => array( 'totalsType' => '' ),
't_meeting_desc' => array( 'totalsType' => '' ),
't_meeting_from_date' => array( 'totalsType' => '' ),
't_meeting_to_date' => array( 'totalsType' => '' ),
't_meeting_from_time' => array( 'totalsType' => '' ),
't_meeting_to_time' => array( 'totalsType' => '' ),
'user_participant_list' => array( 'totalsType' => '' ),
't_meeting_participant_type' => array( 'totalsType' => '' ),
't_meeting_total_participant' => array( 'totalsType' => '' ),
't_meeting_isminuman' => array( 'totalsType' => '' ),
't_meeting_issnack' => array( 'totalsType' => '' ),
't_meeting_ismakan' => array( 'totalsType' => '' ),
't_meeting_recurring_flag' => array( 'totalsType' => '' ),
't_meeting_status' => array( 'totalsType' => '' ),
'add_user' => array( 'totalsType' => '' ),
'add_date' => array( 'totalsType' => '' ),
'edit_user' => array( 'totalsType' => '' ),
'edit_date' => array( 'totalsType' => '' ),
'fr_date' => array( 'totalsType' => '' ),
'to_dt' => array( 'totalsType' => '' ),
'fr_time' => array( 'totalsType' => '' ),
'to_time' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 't_meeting_id',
't_meeting_roomid',
't_meeting_no',
't_meeting_user',
't_meeting_desc',
't_meeting_from_date',
't_meeting_to_date',
't_meeting_from_time',
't_meeting_to_time',
'user_participant_list',
't_meeting_participant_type',
't_meeting_total_participant',
't_meeting_isminuman',
't_meeting_issnack',
't_meeting_ismakan',
't_meeting_recurring_flag',
't_meeting_status',
'add_user',
'add_date',
'edit_user',
'edit_date',
'fr_date',
'to_dt',
'fr_time',
'to_time' ),
'exportFields' => array( 't_meeting_id',
't_meeting_roomid',
't_meeting_no',
't_meeting_user',
't_meeting_desc',
't_meeting_from_date',
't_meeting_to_date',
't_meeting_from_time',
't_meeting_to_time',
'user_participant_list',
't_meeting_participant_type',
't_meeting_total_participant',
't_meeting_isminuman',
't_meeting_issnack',
't_meeting_ismakan',
't_meeting_recurring_flag',
't_meeting_status',
'add_user',
'add_date',
'edit_user',
'edit_date',
'fr_date',
'to_dt',
'fr_time',
'to_time' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 't_meeting_id' => array( 'export_field' ),
't_meeting_roomid' => array( 'export_field1' ),
't_meeting_no' => array( 'export_field2' ),
't_meeting_user' => array( 'export_field3' ),
't_meeting_desc' => array( 'export_field4' ),
't_meeting_from_date' => array( 'export_field5' ),
't_meeting_to_date' => array( 'export_field6' ),
't_meeting_from_time' => array( 'export_field7' ),
't_meeting_to_time' => array( 'export_field8' ),
'user_participant_list' => array( 'export_field9' ),
't_meeting_participant_type' => array( 'export_field10' ),
't_meeting_total_participant' => array( 'export_field11' ),
't_meeting_isminuman' => array( 'export_field12' ),
't_meeting_issnack' => array( 'export_field13' ),
't_meeting_ismakan' => array( 'export_field14' ),
't_meeting_recurring_flag' => array( 'export_field15' ),
't_meeting_status' => array( 'export_field16' ),
'add_user' => array( 'export_field17' ),
'add_date' => array( 'export_field18' ),
'edit_user' => array( 'export_field19' ),
'edit_date' => array( 'export_field20' ),
'fr_date' => array( 'export_field21' ),
'to_dt' => array( 'export_field22' ),
'fr_time' => array( 'export_field23' ),
'to_time' => array( 'export_field24' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 't_meeting_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 't_meeting_roomid',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 't_meeting_no',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 't_meeting_user',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 't_meeting_desc',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 't_meeting_from_date',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 't_meeting_to_date',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 't_meeting_from_time',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 't_meeting_to_time',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'user_participant_list',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 't_meeting_participant_type',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 't_meeting_total_participant',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 't_meeting_isminuman',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 't_meeting_issnack',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 't_meeting_ismakan',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 't_meeting_recurring_flag',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 't_meeting_status',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'add_user',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'add_date',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'edit_user',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'edit_date',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'fr_date',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'to_dt',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'fr_time',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'to_time',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>