<?php
			$optionsArray = array( 'totals' => array( 'idt_output' => array( 'totalsType' => '' ),
'dtexe' => array( 'totalsType' => '' ),
'id_client_profile' => array( 'totalsType' => '' ),
'client_name' => array( 'totalsType' => '' ),
'flag_client_type' => array( 'totalsType' => '' ),
'flag_domestic_type_id' => array( 'totalsType' => '' ),
'flag_overseas_type_id' => array( 'totalsType' => '' ),
'flag_client_gender' => array( 'totalsType' => '' ),
'flag_dob_place' => array( 'totalsType' => '' ),
'flag_dob_date' => array( 'totalsType' => '' ),
'flag_address_domicile' => array( 'totalsType' => '' ),
'flag_address_correspondence' => array( 'totalsType' => '' ),
'flag_establishment_place' => array( 'totalsType' => '' ),
'flag_establishment_date' => array( 'totalsType' => '' ),
'flag_tax_number' => array( 'totalsType' => '' ),
'flag_tax_name' => array( 'totalsType' => '' ),
'flag_id_card_number' => array( 'totalsType' => '' ),
'flag_id_card_name' => array( 'totalsType' => '' ),
'flag_id_card_citizen' => array( 'totalsType' => '' ),
'flag_id_card_expired_date' => array( 'totalsType' => '' ),
'flag_contact_pic_name' => array( 'totalsType' => '' ),
'flag_contact_pic_number' => array( 'totalsType' => '' ),
'flag_bank_info' => array( 'totalsType' => '' ),
'flag_refferral' => array( 'totalsType' => '' ),
'flag_fill' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'idt_output',
'dtexe',
'id_client_profile',
'client_name',
'flag_client_type',
'flag_domestic_type_id',
'flag_overseas_type_id',
'flag_client_gender',
'flag_dob_place',
'flag_dob_date',
'flag_address_domicile',
'flag_address_correspondence',
'flag_establishment_place',
'flag_establishment_date',
'flag_tax_number',
'flag_tax_name',
'flag_id_card_number',
'flag_id_card_name',
'flag_id_card_citizen',
'flag_id_card_expired_date',
'flag_contact_pic_name',
'flag_contact_pic_number',
'flag_bank_info',
'flag_refferral',
'flag_fill' ),
'exportFields' => array( 'idt_output',
'dtexe',
'id_client_profile',
'client_name',
'flag_client_type',
'flag_domestic_type_id',
'flag_overseas_type_id',
'flag_client_gender',
'flag_dob_place',
'flag_dob_date',
'flag_address_domicile',
'flag_address_correspondence',
'flag_establishment_place',
'flag_establishment_date',
'flag_tax_number',
'flag_tax_name',
'flag_id_card_number',
'flag_id_card_name',
'flag_id_card_citizen',
'flag_id_card_expired_date',
'flag_contact_pic_name',
'flag_contact_pic_number',
'flag_bank_info',
'flag_refferral',
'flag_fill' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'idt_output' => array( 'export_field' ),
'dtexe' => array( 'export_field1' ),
'id_client_profile' => array( 'export_field2' ),
'client_name' => array( 'export_field3' ),
'flag_client_type' => array( 'export_field4' ),
'flag_domestic_type_id' => array( 'export_field5' ),
'flag_overseas_type_id' => array( 'export_field6' ),
'flag_client_gender' => array( 'export_field7' ),
'flag_dob_place' => array( 'export_field8' ),
'flag_dob_date' => array( 'export_field9' ),
'flag_address_domicile' => array( 'export_field10' ),
'flag_address_correspondence' => array( 'export_field11' ),
'flag_establishment_place' => array( 'export_field12' ),
'flag_establishment_date' => array( 'export_field13' ),
'flag_tax_number' => array( 'export_field14' ),
'flag_tax_name' => array( 'export_field15' ),
'flag_id_card_number' => array( 'export_field16' ),
'flag_id_card_name' => array( 'export_field17' ),
'flag_id_card_citizen' => array( 'export_field18' ),
'flag_id_card_expired_date' => array( 'export_field19' ),
'flag_contact_pic_name' => array( 'export_field20' ),
'flag_contact_pic_number' => array( 'export_field21' ),
'flag_bank_info' => array( 'export_field22' ),
'flag_refferral' => array( 'export_field23' ),
'flag_fill' => array( 'export_field24' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'idt_output',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'dtexe',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'id_client_profile',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'client_name',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'flag_client_type',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'flag_domestic_type_id',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'flag_overseas_type_id',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'flag_client_gender',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'flag_dob_place',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'flag_dob_date',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'flag_address_domicile',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'flag_address_correspondence',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'flag_establishment_place',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'flag_establishment_date',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'flag_tax_number',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'flag_tax_name',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'flag_id_card_number',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'flag_id_card_name',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'flag_id_card_citizen',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'flag_id_card_expired_date',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'flag_contact_pic_name',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'flag_contact_pic_number',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'flag_bank_info',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'flag_refferral',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'flag_fill',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>