<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'idt_output',
'dtexe',
'id_client_profile',
'client_name',
'flag_client_type',
'flag_domestic_type_id',
'flag_overseas_type_id',
'flag_client_gender',
'flag_dob_place',
'flag_dob_date',
'flag_address_domicile',
'flag_address_correspondence',
'flag_establishment_place',
'flag_establishment_date',
'flag_tax_number',
'flag_tax_name',
'flag_id_card_number',
'flag_id_card_name',
'flag_id_card_citizen',
'flag_id_card_expired_date',
'flag_contact_pic_name',
'flag_contact_pic_number',
'flag_bank_info',
'flag_refferral',
'flag_fill' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'idt_output' => array( 'import_field' ),
'dtexe' => array( 'import_field1' ),
'id_client_profile' => array( 'import_field2' ),
'client_name' => array( 'import_field3' ),
'flag_client_type' => array( 'import_field4' ),
'flag_domestic_type_id' => array( 'import_field5' ),
'flag_overseas_type_id' => array( 'import_field6' ),
'flag_client_gender' => array( 'import_field7' ),
'flag_dob_place' => array( 'import_field8' ),
'flag_dob_date' => array( 'import_field9' ),
'flag_address_domicile' => array( 'import_field10' ),
'flag_address_correspondence' => array( 'import_field11' ),
'flag_establishment_place' => array( 'import_field12' ),
'flag_establishment_date' => array( 'import_field13' ),
'flag_tax_number' => array( 'import_field14' ),
'flag_tax_name' => array( 'import_field15' ),
'flag_id_card_number' => array( 'import_field16' ),
'flag_id_card_name' => array( 'import_field17' ),
'flag_id_card_citizen' => array( 'import_field18' ),
'flag_id_card_expired_date' => array( 'import_field19' ),
'flag_contact_pic_name' => array( 'import_field20' ),
'flag_contact_pic_number' => array( 'import_field21' ),
'flag_bank_info' => array( 'import_field22' ),
'flag_refferral' => array( 'import_field23' ),
'flag_fill' => array( 'import_field24' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'idt_output',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'dtexe',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'id_client_profile',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'client_name',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'flag_client_type',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'flag_domestic_type_id',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'flag_overseas_type_id',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'flag_client_gender',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'flag_dob_place',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'flag_dob_date',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'flag_address_domicile',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'flag_address_correspondence',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'flag_establishment_place',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'flag_establishment_date',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'flag_tax_number',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'flag_tax_name',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'flag_id_card_number',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'flag_id_card_name',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'flag_id_card_citizen',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'flag_id_card_expired_date',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'flag_contact_pic_name',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'flag_contact_pic_number',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'flag_bank_info',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'flag_refferral',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'flag_fill',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>