<?php
			$optionsArray = array( 'totals' => array( 't_register_id' => array( 'totalsType' => '' ),
't_register_id_x' => array( 'totalsType' => '' ),
't_register_no' => array( 'totalsType' => '' ),
't_register_date' => array( 'totalsType' => '' ),
't_register_source' => array( 'totalsType' => '' ),
't_register_location_id' => array( 'totalsType' => '' ),
't_register_transfer_fl' => array( 'totalsType' => '' ),
't_register_transfer_location_id' => array( 'totalsType' => '' ),
't_register_transfer_date' => array( 'totalsType' => '' ),
't_register_transfer_courier' => array( 'totalsType' => '' ),
't_register_doc_from' => array( 'totalsType' => '' ),
't_register_doc_owner' => array( 'totalsType' => '' ),
't_register_doc_user' => array( 'totalsType' => '' ),
't_register_images' => array( 'totalsType' => '' ),
't_register_note' => array( 'totalsType' => '' ),
't_register_status' => array( 'totalsType' => '' ),
'add_user' => array( 'totalsType' => '' ),
'add_date' => array( 'totalsType' => '' ),
'edit_user' => array( 'totalsType' => '' ),
'edit_date' => array( 'totalsType' => '' ),
'nomor' => array( 'totalsType' => '' ),
'digit' => array( 'totalsType' => '' ),
'add_sign_user' => array( 'totalsType' => '' ),
'add_sign_date' => array( 'totalsType' => '' ),
'add_sign_fl' => array( 'totalsType' => '' ),
'last_user' => array( 'totalsType' => '' ),
'last_date' => array( 'totalsType' => '' ),
't_register_feedback_date' => array( 'totalsType' => '' ),
't_register_feedback_time' => array( 'totalsType' => '' ),
't_register_feedback_signature' => array( 'totalsType' => '' ),
't_register_feedback_takephoto' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 't_register_id',
't_register_id_x',
't_register_no',
't_register_date',
't_register_source',
't_register_location_id',
't_register_transfer_fl',
't_register_transfer_location_id',
't_register_transfer_date',
't_register_transfer_courier',
't_register_doc_from',
't_register_doc_owner',
't_register_images',
't_register_note',
't_register_status',
'add_user',
'add_date',
'edit_user',
'edit_date',
'nomor',
'digit',
't_register_doc_user',
'add_sign_user',
'add_sign_date',
'add_sign_fl',
'last_user',
'last_date',
't_register_feedback_date',
't_register_feedback_time',
't_register_feedback_signature',
't_register_feedback_takephoto' ),
'exportFields' => array( 't_register_id',
't_register_id_x',
't_register_no',
't_register_date',
't_register_source',
't_register_location_id',
't_register_transfer_fl',
't_register_transfer_location_id',
't_register_transfer_date',
't_register_transfer_courier',
't_register_doc_from',
't_register_doc_owner',
't_register_images',
't_register_note',
't_register_status',
'add_user',
'add_date',
'edit_user',
'edit_date',
'nomor',
'digit',
't_register_doc_user',
'add_sign_user',
'add_sign_date',
'add_sign_fl',
'last_user',
'last_date',
't_register_feedback_date',
't_register_feedback_time',
't_register_feedback_signature',
't_register_feedback_takephoto' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 't_register_id' => array( 'export_field' ),
't_register_id_x' => array( 'export_field1' ),
't_register_no' => array( 'export_field2' ),
't_register_date' => array( 'export_field3' ),
't_register_source' => array( 'export_field4' ),
't_register_location_id' => array( 'export_field5' ),
't_register_transfer_fl' => array( 'export_field6' ),
't_register_transfer_location_id' => array( 'export_field7' ),
't_register_transfer_date' => array( 'export_field8' ),
't_register_transfer_courier' => array( 'export_field9' ),
't_register_doc_from' => array( 'export_field10' ),
't_register_doc_owner' => array( 'export_field11' ),
't_register_images' => array( 'export_field12' ),
't_register_note' => array( 'export_field13' ),
't_register_status' => array( 'export_field14' ),
'add_user' => array( 'export_field15' ),
'add_date' => array( 'export_field16' ),
'edit_user' => array( 'export_field17' ),
'edit_date' => array( 'export_field18' ),
'nomor' => array( 'export_field19' ),
'digit' => array( 'export_field20' ),
't_register_doc_user' => array( 'export_field21' ),
'add_sign_user' => array( 'export_field22' ),
'add_sign_date' => array( 'export_field23' ),
'add_sign_fl' => array( 'export_field24' ),
'last_user' => array( 'export_field25' ),
'last_date' => array( 'export_field26' ),
't_register_feedback_date' => array( 'export_field27' ),
't_register_feedback_time' => array( 'export_field28' ),
't_register_feedback_signature' => array( 'export_field29' ),
't_register_feedback_takephoto' => array( 'export_field30' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 't_register_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 't_register_id_x',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 't_register_no',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 't_register_date',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 't_register_source',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 't_register_location_id',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 't_register_transfer_fl',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 't_register_transfer_location_id',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 't_register_transfer_date',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 't_register_transfer_courier',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 't_register_doc_from',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 't_register_doc_owner',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 't_register_images',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 't_register_note',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 't_register_status',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'add_user',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'add_date',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'edit_user',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'edit_date',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'nomor',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'digit',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 't_register_doc_user',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'add_sign_user',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'add_sign_date',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'add_sign_fl',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'last_user',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'last_date',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 't_register_feedback_date',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 't_register_feedback_time',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 't_register_feedback_signature',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 't_register_feedback_takephoto',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>