<?php
$dalTablem_employee = array();
$dalTablem_employee["id"] = array("type"=>3,"varname"=>"id", "name" => "id", "autoInc" => "1");
$dalTablem_employee["prid"] = array("type"=>200,"varname"=>"prid", "name" => "prid", "autoInc" => "0");
$dalTablem_employee["comid"] = array("type"=>200,"varname"=>"comid", "name" => "comid", "autoInc" => "0");
$dalTablem_employee["nik"] = array("type"=>200,"varname"=>"nik", "name" => "nik", "autoInc" => "0");
$dalTablem_employee["nama"] = array("type"=>200,"varname"=>"nama", "name" => "nama", "autoInc" => "0");
$dalTablem_employee["email"] = array("type"=>200,"varname"=>"email", "name" => "email", "autoInc" => "0");
$dalTablem_employee["position"] = array("type"=>200,"varname"=>"position", "name" => "position", "autoInc" => "0");
$dalTablem_employee["norekbca"] = array("type"=>200,"varname"=>"norekbca", "name" => "norekbca", "autoInc" => "0");
$dalTablem_employee["secdate"] = array("type"=>135,"varname"=>"secdate", "name" => "secdate", "autoInc" => "0");
$dalTablem_employee["secuser"] = array("type"=>200,"varname"=>"secuser", "name" => "secuser", "autoInc" => "0");
$dalTablem_employee["gender"] = array("type"=>200,"varname"=>"gender", "name" => "gender", "autoInc" => "0");
$dalTablem_employee["agama"] = array("type"=>200,"varname"=>"agama", "name" => "agama", "autoInc" => "0");
$dalTablem_employee["birthplace"] = array("type"=>200,"varname"=>"birthplace", "name" => "birthplace", "autoInc" => "0");
$dalTablem_employee["birthday"] = array("type"=>135,"varname"=>"birthday", "name" => "birthday", "autoInc" => "0");
$dalTablem_employee["noktp"] = array("type"=>200,"varname"=>"noktp", "name" => "noktp", "autoInc" => "0");
$dalTablem_employee["nokk"] = array("type"=>200,"varname"=>"nokk", "name" => "nokk", "autoInc" => "0");
$dalTablem_employee["nohp"] = array("type"=>200,"varname"=>"nohp", "name" => "nohp", "autoInc" => "0");
$dalTablem_employee["emailpribadi"] = array("type"=>200,"varname"=>"emailpribadi", "name" => "emailpribadi", "autoInc" => "0");
$dalTablem_employee["alamatktp"] = array("type"=>200,"varname"=>"alamatktp", "name" => "alamatktp", "autoInc" => "0");
$dalTablem_employee["alamatdom"] = array("type"=>200,"varname"=>"alamatdom", "name" => "alamatdom", "autoInc" => "0");
$dalTablem_employee["datejoin"] = array("type"=>135,"varname"=>"datejoin", "name" => "datejoin", "autoInc" => "0");
$dalTablem_employee["dateangkat"] = array("type"=>135,"varname"=>"dateangkat", "name" => "dateangkat", "autoInc" => "0");
$dalTablem_employee["isaktif"] = array("type"=>13,"varname"=>"isaktif", "name" => "isaktif", "autoInc" => "0");
$dalTablem_employee["nonpwp"] = array("type"=>200,"varname"=>"nonpwp", "name" => "nonpwp", "autoInc" => "0");
$dalTablem_employee["npbjpskes"] = array("type"=>200,"varname"=>"npbjpskes", "name" => "npbjpskes", "autoInc" => "0");
$dalTablem_employee["nobpjstk"] = array("type"=>200,"varname"=>"nobpjstk", "name" => "nobpjstk", "autoInc" => "0");
$dalTablem_employee["nopaspor"] = array("type"=>200,"varname"=>"nopaspor", "name" => "nopaspor", "autoInc" => "0");
$dalTablem_employee["statustax"] = array("type"=>200,"varname"=>"statustax", "name" => "statustax", "autoInc" => "0");
$dalTablem_employee["daruratnama"] = array("type"=>200,"varname"=>"daruratnama", "name" => "daruratnama", "autoInc" => "0");
$dalTablem_employee["darurathub"] = array("type"=>200,"varname"=>"darurathub", "name" => "darurathub", "autoInc" => "0");
$dalTablem_employee["darurattelp"] = array("type"=>200,"varname"=>"darurattelp", "name" => "darurattelp", "autoInc" => "0");
$dalTablem_employee["userid"] = array("type"=>200,"varname"=>"userid", "name" => "userid", "autoInc" => "0");
$dalTablem_employee["level"] = array("type"=>200,"varname"=>"level", "name" => "level", "autoInc" => "0");
$dalTablem_employee["uprid"] = array("type"=>200,"varname"=>"uprid", "name" => "uprid", "autoInc" => "0");
$dalTablem_employee["statuskawin"] = array("type"=>200,"varname"=>"statuskawin", "name" => "statuskawin", "autoInc" => "0");
$dalTablem_employee["jmlanak"] = array("type"=>3,"varname"=>"jmlanak", "name" => "jmlanak", "autoInc" => "0");
$dalTablem_employee["noasuransi"] = array("type"=>200,"varname"=>"noasuransi", "name" => "noasuransi", "autoInc" => "0");
$dalTablem_employee["nopks"] = array("type"=>200,"varname"=>"nopks", "name" => "nopks", "autoInc" => "0");
$dalTablem_employee["dpks"] = array("type"=>200,"varname"=>"dpks", "name" => "dpks", "autoInc" => "0");
$dalTablem_employee["handler"] = array("type"=>200,"varname"=>"handler", "name" => "handler", "autoInc" => "0");
$dalTablem_employee["is_active"] = array("type"=>16,"varname"=>"is_active", "name" => "is_active", "autoInc" => "0");
$dalTablem_employee["is_delete"] = array("type"=>16,"varname"=>"is_delete", "name" => "is_delete", "autoInc" => "0");
$dalTablem_employee["deleted_date"] = array("type"=>135,"varname"=>"deleted_date", "name" => "deleted_date", "autoInc" => "0");
$dalTablem_employee["created_date"] = array("type"=>135,"varname"=>"created_date", "name" => "created_date", "autoInc" => "0");
$dalTablem_employee["created_by"] = array("type"=>200,"varname"=>"created_by", "name" => "created_by", "autoInc" => "0");
$dalTablem_employee["last_update_by"] = array("type"=>3,"varname"=>"last_update_by", "name" => "last_update_by", "autoInc" => "0");
$dalTablem_employee["last_update_date"] = array("type"=>135,"varname"=>"last_update_date", "name" => "last_update_date", "autoInc" => "0");
$dalTablem_employee["id"]["key"]=true;

$dal_info["u736239518tsundbat154412412__tblm_employee"] = &$dalTablem_employee;
?>