<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_home  extends eventsBase
{
	function __construct()
	{
	// fill list of events

	}

//	handlers


		// dashboatd snippets function
	function event_home_snippet( &$header, &$icon )
	{
		$header = "Calender Event";
$userData = Security::getUserName();
//**********  Check if specific record exists  ************

$rs = CustomQuery("select url_calender from m_login where username='".$userData."'");
$data=db_fetch_array($rs);
$calender = $data["url_calender"];

echo "<iframe src='".$calender."' height='1024' width='100%'></iframe>";

;
	}
		// dashboatd snippets function
	function event_home_snippet1( &$header, &$icon )
	{
		require "myCode/Events_home.html";;
	}
		// dashboatd snippets function
	function event_home_snippet2( &$header, &$icon )
	{
		require "myCode/Events_home2.html";;
	}
		// dashboatd snippets function
	function event_home_snippet3( &$header, &$icon )
	{
		require "myCode/Events_home2.html";;
	}
		// dashboatd snippets function
	function event_home_snippet5( &$header, &$icon )
	{
		require "myCode/index.html";;
	}
		// dashboatd snippets function
	function event_home_snippet6( &$header, &$icon )
	{
		$userData = Security::getUserName();

$sqllogin="select url_calender from m_login where username='".$userData."'";
$rslogin=CustomQuery($sqllogin);
$datalogin=db_fetch_array($rslogin);





$header = "Outlook Calender";
$html="<iframe src='".$datalogin['url_calender']."' width='100%' height='1024' title='W3Schools Free Online Web Tutorials' style='border:none;'></iframe>";
echo $html;;
	}
		// dashboatd snippets function
	function event_home_snippet7( &$header, &$icon )
	{
		$header="instagram";
require "instagram.html";;
	}
		// dashboatd snippets function
	function event_home_snippet8( &$header, &$icon )
	{
		$html = "<div class='card-container'><div class='card'><div class='card-image'><img src='https://via.placeholder.com/50' alt='Profile Image'><div class='status'></div></div><div class='card-content'><h4>Welcome, Manuel Dios!</h4><p>Information Technology</p></div><div class='options'></div></div><div class='announcement'><h4>Announcements</h4><p>We ll be hosting a townhall meeting to discuss this years events.</p><div class='options'></div></div></div>";

echo $html;;
	}

}
?>