<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_m_disposition_profile  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeMoveNextList"]=true;

		$this->events["AfterAdd"]=true;

		$this->events["BeforeAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		
if ($data["t_disposition_status"] !='15')
{

$pageObject->showItem("add");


}
else
if ($data["t_disposition_status"] =='15')
{

$pageObject->hideItem("add");


}

$rs = DB::Query("select * from m_disposition where t_disposition_no=".$data["t_disposition_no"]." and t_disposition_type=1 order by t_disposition_id desc limit 1");
while( $data = $rs->fetchAssoc() )
{
$status = $data["t_disposition_status"];
}

if ($status == '15')
{

$pageObject->hideItem("add");


}
else
{

$pageObject->showItem("add");

}
// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		CustomQuery("call sp_profile_new_flow(".$values["t_disposition_id"].",".$values["t_disposition_no"].")");

$rs = DB::Query("SELECT m_disposition.t_disposition_id, m_disposition.t_disposition_no,m_status.status FROM m_disposition INNER JOIN m_status ON m_disposition.t_disposition_status = m_status.m_status_id where m_disposition.t_disposition_id=".$values["t_disposition_id"]);
while( $data = $rs->fetchAssoc() )
{
$status = $data["status"];
$message="You receive a disposition from ".$values["t_disposition_from"];
$title = "[T-Mail] ".$status." Profile Registration Notification";
$icon = "fa-envelope"; 
$url = makePageLink( "m_client_profile", "Edit", $keys) ; 
$expire = 1440; 
$permissions = $values["t_disposition_to"]; 
$newWindow = false;

addNotification( $message,$title,$icon,$url,$expire,$permissions,$newWindow);  


}


;
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		$userData = Security::getUserName();
//**********  Check if specific record exists  ************Select count(*) as val from m_mapping_disposition where pic_employee_username = USER and by_employee_username = user_add
$sql="select add_user from m_client_profile where id ='".$values["t_disposition_no"]."'";
$rs=CustomQuery($sql);
$data=db_fetch_array($rs);

$sql2="Select * from m_mapping_disposition where pic_employee_username ='".$userData."' and by_employee_username ='".$data["add_user"]."'";
$rs2=CustomQuery($sql2);
$data2=db_fetch_array($rs2);


	if (!$data2)
	{
		if ($values["t_disposition_status"]!= 12)
		{
			$tz = 'Asia/Jakarta';
			$dt = new DateTime("now", new DateTimeZone($tz));
			$timestamp = $dt->format('Y-m-d h:i:s');
			$tahun = $dt->format("y");
			$bulan = $dt->format("m");
			$tanggal = $dt->format("d");

			$values["t_disposition_from"] = $userData;
			$values["t_disposition_from_date"] = $timestamp;
			$values["t_disposition_to_date"] = $timestamp;
			$values["t_disposition_type"] = 2;
			return true;
		}
		else

		if ($values["t_disposition_status"]== 12)

		{

			$message="Your Account can't approved this document";
			return false;
		}
	}
	else
	if ($data2 && $values["t_disposition_status"]!= 15)
	{  
		$tz = 'Asia/Jakarta';
		$dt = new DateTime("now", new DateTimeZone($tz));
		$timestamp = $dt->format('Y-m-d h:i:s');
		$tahun = $dt->format("y");
		$bulan = $dt->format("m");
		$tanggal = $dt->format("d");

		$values["t_disposition_from"] = $userData;
		$values["t_disposition_from_date"] = $timestamp;
		$values["t_disposition_to_date"] = $timestamp;
		$values["t_disposition_type"] = 1;
		return true;
	}
else
if ($data2 && $values["t_disposition_status"]== 12)
	{  
		$tz = 'Asia/Jakarta';
		$dt = new DateTime("now", new DateTimeZone($tz));
		$timestamp = $dt->format('Y-m-d h:i:s');
		$tahun = $dt->format("y");
		$bulan = $dt->format("m");
		$tanggal = $dt->format("d");

		$values["t_disposition_from"] = $userData;
		$values["t_disposition_from_date"] = $timestamp;
		$values["t_disposition_to_date"] = $timestamp;
		$values["t_disposition_type"] = 1;
		return true;
	}
	

;
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>