<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'activationField' => '˂Create new˃',
'active' => true,
'code' => '00',
'codeField' => 'totp',
'emailField' => 'email',
'extUserIdField' => 'ext_security_id',
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'phoneField' => 'phone',
'resetDateField' => 'reset_date',
'resetTokenField' => 'reset_token',
'table' => array( 'connId' => 'u736239518tsundbat154412412',
'table' => 'm_login' ),
'twoFactorField' => 'two_factor',
'userGroupField' => 'username',
'usernameField' => 'username',
'userpicField' => 'userpic' ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'NOCna9fiUuIdixzEORyz',
'JWTSecret' => 'nlSELthCVPm9BOgUSnVy',
'forceExpire' => true,
'keepAlive' => false ),
'registration' => array( 'passwordValidation' => array( 'strong' => true,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => true ),
'remindMethod' => 0,
'hashAlgorithm' => 0,
'caseInsensitiveLogin' => false,
'changePasswordPage' => true,
'changePwdPage' => true,
'hashPassword' => false,
'registerPage' => false,
'remindPage' => true,
'remindPasswordPage' => true ),
'captchaSettings' => array( 'captchaType' => 1,
'siteKey' => '6LcgMRAqAAAAAOGa-y7QXEag6wAlbj6D_NG1uUrN',
'secretKey' => '6LcgMRAqAAAAACAfrllYWltuffsrvzsZ0pyG_Ka5',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => 'no-reply@talisman.co.id',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'smtp-mail.outlook.com',
'SMTPPort' => 587,
'SMTPUser' => 'no-reply@talisman.co.id',
'SMTPPassword' => 'No2019reply!',
'securityProtocol' => 2 ),
'advancedSecurity' => array( 'allowGuestLogin' => false ),
'auditAndLocking' => array( 'loggingTable' => array( 'connId' => 'u736239518tsundbat154412412',
'table' => 'tsun_gen2__audit' ),
'lockingTable' => array( 'connId' => 'u736239518tsundbat154412412',
'table' => '˂Create new˃' ),
'tables' => array( 'Category' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'Language' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'Siganture' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'Type' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'View' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'admin_members' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'admin_rights' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'admin_users' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'm_announcement' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'm_announcement_view' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'm_asuransi' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'm_bank' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'm_category' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'm_client_profile' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'm_countries' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'm_disposition_inmail' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'm_disposition_type' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'm_division' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'm_domestic_type' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'm_kabupaten' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'm_kecamatan' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'm_kelurahan' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'm_language' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'm_letter_pic' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'm_location_office' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'm_login' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'm_mapping_disposition' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'm_mapping_letter' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'm_mapping_letter_pic' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'm_overseas_type' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'm_position_siganture' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'm_producer' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'm_provinsi' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'm_status' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'm_template' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'm_type' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'members' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'partnership_view' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'sp_disposition_flow' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
't_delivery' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
't_delivery_address' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
't_delivery_details' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
't_delivery_expedition' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
't_delivery_internal' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
't_delivery_type_user' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
't_delivery_x' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
't_letter' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
't_letter_flow' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
't_output_client_profile' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'template' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'v_countries' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'v_m_kabupaten' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'v_m_kecamatan' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'v_m_provinsi' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'v_states' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'v_status' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ) ),
'loggingMode' => 1,
'loggingFile' => 'audit.log',
'logSecurityActions' => true,
'lockAfterUnsuccessfulLogin' => false,
'enableLocking' => false ),
'twoFactorSettings' => array( 'available' => false,
'required' => true,
'enable' => true,
'remember' => true,
'types' => array( 'email' => false,
'phone' => false,
'totp' => true ),
'twoFactorField' => 'two_factor',
'emailField' => 'email',
'phoneField' => 'phone',
'codeField' => 'totp',
'projectName' => 'tsun_gen3' ),
'projectName' => 'tsun_gen3',
'loginDataSource' => 'm_login',
'loginForm' => 0,
'dynamicPermissions' => true,
'dpTablePrefix' => 'Tsun_',
'dpTableConnId' => 'u736239518tsundbat154412412',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'activationField' => '˂Create new˃',
'active' => true,
'code' => '00',
'codeField' => 'totp',
'emailField' => 'email',
'extUserIdField' => 'ext_security_id',
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'phoneField' => 'phone',
'resetDateField' => 'reset_date',
'resetTokenField' => 'reset_token',
'table' => array( 'connId' => 'u736239518tsundbat154412412',
'table' => 'm_login' ),
'twoFactorField' => 'two_factor',
'userGroupField' => 'username',
'usernameField' => 'username',
'userpicField' => 'userpic' ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '00' ),
'notifications' => array( 'enabled' => true,
'table' => array( 'connId' => 'u736239518tsundbat154412412',
'table' => 'tsun_noti' ) ) );
?>