<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_t_booking_approval  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterEdit"]=true;



	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		$ticketId = $values['t_disposition_no'];
$disposisi = $values['t_disposition_status'];
$tglInput = $values['t_disposition_from_date'];
$idDispo = $values['t_disposition_id'];
$dispo = $values['t_disposition_from'];
$bookingid = $values['t_booking_id'];
$vehicle = $values['m_vehicle_id']; 
$dispoto = $values['t_disposition_to'];
$emailUser = $values['t_booking_user'];
$address = $values['t_booking_destination'];
$driver = $values['m_vehicle_driver'];
$remark = $values['t_booking_remarks'];

$vehicleName = '';

switch ($vehicle) { 
    case 1:
        $vehicleName = 'Toyota Grand New Avanza - B 1040 DOC';
        break;
    case 2:
        $vehicleName = 'Toyota All New Avanza 2022';
        break;
    case 3:
        $vehicleName = 'Blue Bird';
        break;
    case 4:
        $vehicleName = 'Pick Up';
        break;
    case 5:
        $vehicleName = 'Toyota Avanza - B 2762 SFV';
        break;
    case 6:
        $vehicleName = 'Toyota Grand New Avanza - B 8587 TI';
        break;
    default:
        $vehicleName = 'Unknown Vehicle';
        break;
}

$message = "You receive a disposition from " . $dispo;
$title = "[T-Booking] " . $disposisi . " Booking Notification";
$icon = "fa-envelope";
$url = "t_booking_view.php?editid1=" . $ticketId;
$expire = 1440;
$permissions = str_replace('@talisman.co.id', '', $emailUser);

$newWindow = false;

addNotification($message, $title, $icon, $url, $expire, $permissions, $newWindow);

$from = "no-reply@talisman.co.id";
$msg = "Your booking request has been approved. Here are the details:\n\n" .
       "Address: " . $address . "\n" .
       "Remarks: " . $remark . "\n" .
       "Driver : " . $driver . "\n" .
       "Vehicle: " . $vehicleName . "\n\n" .
       "Thank you,\n";

$subject = "[T-Booking] Disposition Notification";

$email = $emailUser;
$ret = runner_mail(array('to' => $email, 'subject' => $subject, 'body' => $msg, 'from' => $from));

if (!$ret["mailed"]) {
    echo $ret["message"];
}

;
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>