<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_t_invoice_det  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;

		$this->events["AfterEdit"]=true;

		$this->events["AfterDelete"]=true;



	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		CustomQuery("call sp_calulate_invoice_details(".$values["t_invoice_id"].")");

$html = <<<EOT
<html>
<head>
<meta charset='utf-8' />
</head>
<body>
<div>
New updated request

</div>
<script>
window.parent.location.reload();
</script>
</body>
</html>
EOT;
echo $html;
exit();

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		CustomQuery("call sp_calulate_invoice_details(".$values["t_invoice_id"].")");
$html = <<<EOT
<html>
<head>
<meta charset='utf-8' />
</head>
<body>
<div>
New updated request

</div>
<script>
window.parent.location.reload();
</script>
</body>
</html>
EOT;
echo $html;
exit();

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record deleted
function AfterDelete($where, &$deleted_values, &$message, $pageObject)
{

		CustomQuery("call sp_calulate_invoice_details(".$deleted_values["t_invoice_id"].")");
$html = <<<EOT
<html>
<head>
<meta charset='utf-8' />
</head>
<body>
<div>
New updated request

</div>
<script>
window.parent.location.reload();
</script>
</body>
</html>
EOT;
echo $html;
exit();

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function AfterDelete

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>