<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_t_register  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["BeforeAdd"]=true;

		$this->events["AfterAdd"]=true;

		$this->events["BeforeEdit"]=true;




	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		$sql="select nomor + 1 as nomorberjalan from t_register order by t_register_id desc limit 1";
$rs=CustomQuery($sql);
$data=db_fetch_array($rs);

$values["nomor"] = $data["nomorberjalan"];
$length= 5;
$urut=substr(str_repeat(0, $length).$values["nomor"], - $length);



$userData = Security::getUserName();
$tz = 'Asia/Jakarta';
$dt = new DateTime("now", new DateTimeZone($tz));
$timestamp = $dt->format('Y-m-d h:i:s');
$tahun = $dt->format("y");
$year = $dt->format("Y");
$bulan = $dt->format("m");
$tanggal = $dt->format("d");


$sqllogin="select username from m_login where m_employee_id='".$values["t_register_doc_owner"]."'";
$rslogin=CustomQuery($sqllogin);
$datalogin=db_fetch_array($rslogin);

$values["add_user"] = $userData;
$values["add_date"] = $timestamp;
$values["t_register_doc_user"]=$datalogin["username"];
$values["t_register_no"] = "401.".$urut.".".$bulan.".".$year;
$values["t_register_status"]=16;


// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		$sql="select username  from m_login where m_employee_id='".$values["t_register_doc_owner"]."'";
$rs=CustomQuery($sql);
$data=db_fetch_array($rs);

$keys = $values["t_register_id"];
$status = $data["username"];
$message="You receive a in mail no. ".$values["t_register_no"]." from ".$values["t_register_doc_from"];
$title = "[T-Mail] In Mail Registration notification";
$icon = "fa-envelope";
$url = "t_in_mail_view.php?editid1=".$values["t_register_id"];//makePageLink( "t_in_mail_list", "Edit", $keys) ; 
$expire = 1440; 
$permissions = $data["username"]; 
$newWindow = false;

addNotification( $message,$title,$icon,$url,$expire,$permissions,$newWindow); 

CustomQuery("call sp_register_new_flow(".$values["t_register_id"].")");
// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, $where, &$oldvalues, &$keys, &$message, $inline, $pageObject)
{

		
$userData = Security::getUserName();
$tz = 'Asia/Jakarta';
$dt = new DateTime("now", new DateTimeZone($tz));
$timestamp = $dt->format('Y-m-d h:i:s');
$tahun = $dt->format("y");
$year = $dt->format("Y");
$bulan = $dt->format("m");
$tanggal = $dt->format("d");


$sqllogin="select username from m_login where m_employee_id='".$values["t_register_doc_owner"]."'";
$rslogin=CustomQuery($sqllogin);
$datalogin=db_fetch_array($rslogin);

$values["edit_user"] = $userData;
$values["edit_date"] = $timestamp;
$values["t_register_doc_user"]=$datalogin['username'];



// Place event code here.
// Use "Add Action" button to add code snippets.

return true;

;
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>