<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_v1  extends eventsBase
{
	function __construct()
	{
	// fill list of events

	}

//	handlers


		// dashboatd snippets function
	function event_v1_snippet( &$header, &$icon )
	{
		require "myCode/index.html";;
	}
		// dashboatd snippets function
	function event_v1_snippet1( &$header, &$icon )
	{
		$header = "Leave Balance";
echo "<span style='font-size: 35px;'>20</span>";;
	}
		// dashboatd snippets function
	function event_v1_snippet2( &$header, &$icon )
	{
		$header = "Today Revenue";
echo "<span style='font-size: 35px;'>10.000.000</span>";;
	}
		// dashboatd snippets function
	function event_v1_snippet3( &$header, &$icon )
	{
		$header = "Total Reimbursement ";
echo "<span style='font-size: 35px;'>350.000</span>";;
	}
		// dashboatd snippets function
	function event_v1_snippet5( &$header, &$icon )
	{
		$header = "ANNOUNCEMENT";
echo "Your text here";;
	}
		// dashboatd snippets function
	function event_v1_snippet6( &$header, &$icon )
	{
		$header = "ANNOUNTMENT";
echo "Your text here";;
	}
		// dashboatd snippets function
	function event_v1_snippet7( &$header, &$icon )
	{
		$header = "Your header here";
echo "Your text here";;
	}
		// dashboatd snippets function
	function event_v1_snippet8( &$header, &$icon )
	{
		$header = "QUICK LINK";
;
	}

}
?>